In [33]:
import pandas as pd
import numpy as np
from cpp_poker.cpp_poker import Hand

In [34]:
df = pd.read_parquet("../dfs/compacted_20240430132106.parquet")
df

,prob_P_has_hand_0,prob_P_has_hand_1,prob_P_has_hand_2,prob_P_has_hand_3,prob_P_has_hand_4,prob_P_has_hand_5,prob_P_has_hand_6,prob_P_has_hand_7,prob_P_has_hand_8,prob_P_has_hand_9,...,player_bet_in_stage,player_bet_in_game,opponent_bet_in_stage,opponent_bet_in_game,player_turn,player_has_bet,opponent_has_bet,pot,game_size,stage
0,0.001377,0.000228,0.001744,0.000486,0.000538,0.000434,0.000950,0.001289,0.000914,0.001696,...,14,469,40,495,True,True,True,964,1487,river
1,0.001339,0.000039,0.000013,0.000504,0.000867,0.001299,0.001545,0.000667,0.001549,0.000661,...,11,119,13,121,True,True,True,240,2003,river
2,0.000000,0.001377,0.000651,0.000391,0.001705,0.000569,0.000410,0.001504,0.000090,0.000198,...,110,370,117,377,True,True,True,747,2001,river
3,0.001162,0.001362,0.000000,0.001594,0.001635,0.001112,0.000135,0.001304,0.000315,0.001661,...,0,305,325,630,True,True,True,935,2326,river
4,0.000171,0.000427,0.001027,0.000752,0.000495,0.000646,0.001213,0.000560,0.001425,0.001687,...,0,180,28,208,True,False,True,388,1088,river
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11007,0.001510,0.001131,0.001499,0.000144,0.000465,0.000000,0.000973,0.001789,0.001542,0.001787,...,0,103,45,148,True,False,True,251,1333,river
11008,0.000990,0.001654,0.000506,0.000000,0.000199,0.001468,0.001385,0.001262,0.001167,0.000688,...,0,409,92,501,True,False,True,910,1907,river
11009,0.000293,0.000851,0.001572,0.001028,0.000965,0.001796,0.000691,0.001638,0.001164,0.000123,...,0,143,167,310,True,True,True,453,1442,river
11010,0.001447,0.000098,0.000460,0.000000,0.000387,0.000091,0.001042,0.000552,0.001136,0.000000,...,0,439,118,557,True,False,True,996,2194,river
11011,0.000000,0.000000,0.001349,0.001582,0.000238,0.001067,0.001052,0.001140,0.000851,0.000463,...,0,393,8,401,True,False,True,794,1867,river

In [35]:
card_cols = [col for col in df.columns if col.startswith("public_card")]
df[card_cols]

,public_card_0,public_card_1,public_card_2,public_card_3,public_card_4,public_card_5,public_card_6,public_card_7,public_card_8,public_card_9,...,public_card_42,public_card_43,public_card_44,public_card_45,public_card_46,public_card_47,public_card_48,public_card_49,public_card_50,public_card_51
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11007,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
11008,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11010,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11011,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
assert df[card_cols].sum(axis=1).eq(5).all()

In [37]:
# Check that the error exists
for row in range(df.shape[0]):
    for card, col in enumerate(card_cols):
        if df.loc[row, col] == 1:
            relevant_range_cols = [
                f"prob_P_has_hand_{conf_hand}" for conf_hand in Hand.HANDS_WITH_CARD[card]
            ] + [f"prob_O_has_hand_{conf_hand}" for conf_hand in Hand.HANDS_WITH_CARD[card]]
            range_sum = df.loc[row, relevant_range_cols].sum()
            if range_sum != 0:
                print("Row:", row, "Card:", card, "conflicts with hands")
                print("Row:", row, "Range sum:", range_sum)
                print("Row:", row, df.loc[row, relevant_range_cols])
                break
    else:
        continue
    break

Row: 260 Card: 10 conflicts with hands
Row: 260 Range sum: 0.07603216268205765
Row: 260 prob_P_has_hand_9      0.000643
prob_P_has_hand_59     0.000031
prob_P_has_hand_108    0.000374
prob_P_has_hand_156    0.001243
prob_P_has_hand_203    0.001456
                         ...
prob_O_has_hand_501    0.000513
prob_O_has_hand_502    0.001156
prob_O_has_hand_503    0.000693
prob_O_has_hand_504    0.000877
prob_O_has_hand_505    0.001218
Name: 260, Length: 102, dtype: object

In [38]:
# Fix the error
p1_range_cols = [col for col in df.columns if col.startswith("prob_P_has_hand_")]
opponent_range_cols = [col for col in df.columns if col.startswith("prob_O_has_hand_")]
updated_rows = set()
range_cols_per_card = np.array(
    [
        np.array(
            [f"prob_P_has_hand_{conf_hand}" for conf_hand in Hand.HANDS_WITH_CARD[card]]
            + [
                f"prob_O_has_hand_{conf_hand}"
                for conf_hand in Hand.HANDS_WITH_CARD[card]
            ]
        )
        for card in range(52)
    ]
)
for row in range(df.shape[0]):
    if row % 100 == 0:
        print("Row:", row, end="\r")
    relevant_range_cols = range_cols_per_card[df.loc[row, card_cols] == 1]
    updated_row = False
    for cols in relevant_range_cols:
        range_sum = df.loc[row, cols].sum()
        if range_sum != 0:
            df.loc[row, cols] = 0
            updated_row = True
    if updated_row:
        print("Row:", row, "Fixed")
        updated_rows.add(row)
print("Fixed", len(updated_rows), "rows")

Row: 260 Fixed
Row: 661 Fixed
Row: 662 Fixed
Row: 663 Fixed
Row: 664 Fixed
Row: 665 Fixed
Row: 666 Fixed
Row: 667 Fixed
Row: 668 Fixed
Row: 669 Fixed
Row: 670 Fixed
Row: 671 Fixed
Row: 672 Fixed
Row: 673 Fixed
Row: 674 Fixed
Row: 675 Fixed
Row: 676 Fixed
Row: 677 Fixed
Row: 678 Fixed
Row: 679 Fixed
Row: 680 Fixed
Row: 681 Fixed
Row: 682 Fixed
Row: 683 Fixed
Row: 684 Fixed
Row: 685 Fixed
Row: 686 Fixed
Row: 687 Fixed
Row: 688 Fixed
Row: 689 Fixed
Row: 690 Fixed
Row: 691 Fixed
Row: 692 Fixed
Row: 693 Fixed
Row: 694 Fixed
Row: 695 Fixed
Row: 696 Fixed
Row: 697 Fixed
Row: 698 Fixed
Row: 699 Fixed
Row: 700 Fixed
Row: 701 Fixed
Row: 702 Fixed
Row: 703 Fixed
Row: 704 Fixed
Row: 705 Fixed
Row: 706 Fixed
Row: 707 Fixed
Row: 708 Fixed
Row: 709 Fixed
Row: 710 Fixed
Row: 711 Fixed
Row: 712 Fixed
Row: 713 Fixed
Row: 714 Fixed
Row: 715 Fixed
Row: 716 Fixed
Row: 717 Fixed
Row: 718 Fixed
Row: 719 Fixed
Row: 720 Fixed
Row: 721 Fixed
Row: 722 Fixed
Row: 723 Fixed
Row: 724 Fixed
Row: 725 Fixed
Row: 726 Fixed
Row: 727 Fixed
Row: 728 Fixed
Row: 729 Fixed
Row: 730 Fixed
Row: 731 Fixed
Row: 732 Fixed
Row: 733 Fixed
Row: 734 Fixed
Row: 735 Fixed
Row: 736 Fixed
Row: 737 Fixed
Row: 738 Fixed
Row: 739 Fixed
Row: 740 Fixed
Row: 741 Fixed
Row: 742 Fixed
Row: 743 Fixed
Row: 744 Fixed
Row: 745 Fixed
Row: 746 Fixed
Row: 747 Fixed
Row: 1046 Fixed
Row: 1047 Fixed
Row: 1048 Fixed
Row: 1049 Fixed
Row: 1050 Fixed
Row: 1051 Fixed
Row: 1052 Fixed
Row: 1053 Fixed
Row: 1054 Fixed
Row: 1055 Fixed
Row: 1056 Fixed
Row: 1057 Fixed
Row: 1058 Fixed
Row: 1059 Fixed
Row: 1060 Fixed
Row: 1061 Fixed
Row: 1062 Fixed
Row: 1063 Fixed
Row: 1064 Fixed
Row: 1065 Fixed
Row: 1066 Fixed
Row: 1067 Fixed
Row: 1068 Fixed
Row: 1069 Fixed
Row: 1070 Fixed
Row: 1071 Fixed
Row: 1072 Fixed
Row: 1073 Fixed
Row: 1074 Fixed
Row: 1075 Fixed
Row: 1076 Fixed
Row: 1077 Fixed
Row: 1078 Fixed
Row: 1079 Fixed
Row: 1080 Fixed
Row: 1081 Fixed
Row: 1082 Fixed
Row: 1083 Fixed
Row: 1084 Fixed
Row: 1085 Fixed
Row: 1086 Fixed
Row: 1087 Fixed
Row: 1088 Fixed
Row: 1089 Fixed
Row: 1090 Fixed
Row: 1091 Fixed
Row: 1092 Fixed
Row: 1093 Fixed
Row: 1094 Fixed
Row: 1095 Fixed
Row: 1096 Fixed
Row: 1097 Fixed
Row: 1098 Fixed
Row: 1099 Fixed
Row: 1100 Fixed
Row: 1101 Fixed
Row: 1102 Fixed
Row: 1103 Fixed
Row: 1104 Fixed
Row: 1105 Fixed
Row: 1106 Fixed
Row: 1107 Fixed
Row: 1108 Fixed
Row: 1109 Fixed
Row: 1110 Fixed
Row: 1111 Fixed
Row: 1112 Fixed
Row: 1113 Fixed
Row: 1114 Fixed
Row: 1115 Fixed
Row: 1116 Fixed
Row: 1117 Fixed
Row: 1118 Fixed
Row: 1119 Fixed
Row: 1120 Fixed
Row: 1121 Fixed
Row: 1122 Fixed
Row: 1123 Fixed
Row: 1124 Fixed
Row: 1125 Fixed
Row: 1126 Fixed
Row: 1127 Fixed
Row: 1128 Fixed
Row: 1129 Fixed
Row: 1130 Fixed
Row: 1131 Fixed
Row: 1132 Fixed
Row: 1133 Fixed
Row: 1134 Fixed
Row: 1135 Fixed
Row: 1136 Fixed
Row: 1137 Fixed
Row: 1138 Fixed
Row: 1139 Fixed
Row: 1140 Fixed
Row: 1141 Fixed
Row: 1142 Fixed
Row: 1143 Fixed
Row: 1144 Fixed
Row: 1145 Fixed
Row: 1146 Fixed
Row: 1147 Fixed
Row: 1148 Fixed
Row: 1149 Fixed
Row: 1150 Fixed
Row: 1151 Fixed
Row: 1152 Fixed
Row: 1153 Fixed
Row: 1154 Fixed
Row: 1155 Fixed
Row: 1156 Fixed
Row: 1157 Fixed
Row: 1158 Fixed
Row: 1159 Fixed
Row: 1160 Fixed
Row: 1161 Fixed
Row: 1162 Fixed
Row: 1163 Fixed
Row: 1164 Fixed
Row: 1165 Fixed
Row: 1166 Fixed
Row: 1167 Fixed
Row: 1168 Fixed
Row: 1169 Fixed
Row: 1170 Fixed
Row: 1171 Fixed
Row: 1172 Fixed
Row: 1173 Fixed
Row: 1174 Fixed
Row: 1175 Fixed
Row: 1176 Fixed
Row: 1177 Fixed
Row: 1178 Fixed
Row: 1179 Fixed
Row: 1180 Fixed
Row: 1181 Fixed
Row: 1182 Fixed
Row: 1183 Fixed
Row: 1184 Fixed
Row: 1185 Fixed
Row: 1186 Fixed
Row: 1187 Fixed
Row: 1188 Fixed
Row: 1189 Fixed
Row: 1190 Fixed
Row: 1191 Fixed
Row: 1192 Fixed
Row: 1193 Fixed
Row: 1194 Fixed
Row: 1195 Fixed
Row: 1196 Fixed
Row: 1197 Fixed
Row: 1198 Fixed
Row: 1199 Fixed
Row: 1200 Fixed
Row: 1201 Fixed
Row: 1202 Fixed
Row: 1203 Fixed
Row: 1204 Fixed
Row: 1205 Fixed
Row: 1206 Fixed
Row: 1207 Fixed
Row: 1208 Fixed
Row: 1209 Fixed
Row: 1210 Fixed
Row: 1211 Fixed
Row: 1212 Fixed
Row: 1213 Fixed
Row: 1214 Fixed
Row: 1215 Fixed
Row: 1216 Fixed
Row: 1217 Fixed
Row: 1218 Fixed
Row: 1219 Fixed
Row: 1220 Fixed
Row: 1221 Fixed
Row: 1222 Fixed
Row: 1223 Fixed
Row: 1224 Fixed
Row: 1225 Fixed
Row: 1226 Fixed
Row: 1227 Fixed
Row: 1228 Fixed
Row: 1229 Fixed
Row: 1230 Fixed
Row: 1231 Fixed
Row: 1232 Fixed
Row: 1233 Fixed
Row: 1234 Fixed
Row: 1235 Fixed
Row: 1236 Fixed
Row: 1237 Fixed
Row: 1238 Fixed
Row: 1239 Fixed
Row: 1240 Fixed
Row: 1241 Fixed
Row: 1242 Fixed
Row: 1243 Fixed
Row: 1244 Fixed
Row: 1245 Fixed
Row: 1246 Fixed
Row: 1247 Fixed
Row: 1248 Fixed
Row: 1249 Fixed
Row: 1250 Fixed
Row: 1251 Fixed
Row: 1252 Fixed
Row: 1253 Fixed
Row: 1254 Fixed
Row: 1255 Fixed
Row: 1256 Fixed
Row: 1257 Fixed
Row: 1258 Fixed
Row: 1259 Fixed
Row: 1260 Fixed
Row: 1261 Fixed
Row: 1262 Fixed
Row: 1263 Fixed
Row: 1264 Fixed
Row: 1265 Fixed
Row: 1266 Fixed
Row: 1267 Fixed
Row: 1268 Fixed
Row: 1269 Fixed
Row: 1270 Fixed
Row: 1271 Fixed
Row: 1272 Fixed
Row: 1273 Fixed
Row: 1274 Fixed
Row: 1275 Fixed
Row: 1276 Fixed
Row: 1277 Fixed
Row: 1278 Fixed
Row: 1279 Fixed
Row: 1280 Fixed
Row: 1281 Fixed
Row: 1282 Fixed
Row: 1283 Fixed
Row: 1284 Fixed
Row: 1285 Fixed
Row: 1286 Fixed
Row: 1287 Fixed
Row: 1288 Fixed
Row: 1289 Fixed
Row: 1290 Fixed
Row: 1291 Fixed
Row: 1292 Fixed
Row: 1293 Fixed
Row: 1294 Fixed
Row: 1295 Fixed
Row: 1296 Fixed
Row: 1297 Fixed
Row: 1298 Fixed
Row: 1299 Fixed
Row: 1300 Fixed
Row: 1301 Fixed
Row: 1302 Fixed
Row: 1303 Fixed
Row: 1304 Fixed
Row: 1305 Fixed
Row: 1306 Fixed
Row: 1307 Fixed
Row: 1308 Fixed
Row: 1309 Fixed
Row: 1310 Fixed
Row: 1311 Fixed
Row: 1312 Fixed
Row: 1313 Fixed
Row: 1314 Fixed
Row: 1315 Fixed
Row: 1316 Fixed
Row: 1317 Fixed
Row: 1318 Fixed
Row: 1319 Fixed
Row: 1320 Fixed
Row: 1321 Fixed
Row: 1322 Fixed
Row: 1323 Fixed
Row: 1324 Fixed
Row: 1325 Fixed
Row: 1326 Fixed
Row: 1327 Fixed
Row: 1328 Fixed
Row: 1329 Fixed
Row: 1330 Fixed
Row: 1331 Fixed
Row: 1332 Fixed
Row: 1333 Fixed
Row: 1334 Fixed
Row: 1335 Fixed
Row: 1336 Fixed
Row: 1337 Fixed
Row: 1338 Fixed
Row: 1339 Fixed
Row: 1340 Fixed
Row: 1341 Fixed
Row: 1342 Fixed
Row: 1343 Fixed
Row: 1344 Fixed
Row: 1345 Fixed
Row: 1346 Fixed
Row: 1347 Fixed
Row: 1348 Fixed
Row: 1349 Fixed
Row: 1350 Fixed
Row: 1351 Fixed
Row: 1352 Fixed
Row: 1353 Fixed
Row: 1354 Fixed
Row: 1355 Fixed
Row: 1356 Fixed
Row: 1357 Fixed
Row: 1358 Fixed
Row: 1359 Fixed
Row: 1360 Fixed
Row: 1361 Fixed
Row: 1362 Fixed
Row: 1363 Fixed
Row: 1364 Fixed
Row: 1365 Fixed
Row: 1366 Fixed
Row: 1367 Fixed
Row: 1368 Fixed
Row: 1369 Fixed
Row: 1370 Fixed
Row: 1371 Fixed
Row: 1372 Fixed
Row: 1373 Fixed
Row: 1374 Fixed
Row: 1375 Fixed
Row: 1376 Fixed
Row: 1377 Fixed
Row: 1378 Fixed
Row: 1379 Fixed
Row: 1380 Fixed
Row: 1381 Fixed
Row: 1382 Fixed
Row: 1383 Fixed
Row: 1384 Fixed
Row: 1385 Fixed
Row: 1386 Fixed
Row: 1387 Fixed
Row: 1388 Fixed
Row: 1389 Fixed
Row: 1390 Fixed
Row: 1391 Fixed
Row: 1392 Fixed
Row: 1393 Fixed
Row: 1394 Fixed
Row: 1395 Fixed
Row: 1396 Fixed
Row: 1397 Fixed
Row: 1398 Fixed
Row: 1399 Fixed
Row: 1400 Fixed
Row: 1401 Fixed
Row: 1402 Fixed
Row: 1403 Fixed
Row: 1404 Fixed
Row: 1405 Fixed
Row: 1406 Fixed
Row: 1407 Fixed
Row: 1408 Fixed
Row: 1409 Fixed
Row: 1410 Fixed
Row: 1411 Fixed
Row: 1412 Fixed
Row: 1413 Fixed
Row: 1414 Fixed
Row: 1415 Fixed
Row: 1416 Fixed
Row: 1417 Fixed
Row: 1418 Fixed
Row: 1419 Fixed
Row: 1420 Fixed
Row: 1421 Fixed
Row: 1422 Fixed
Row: 1423 Fixed
Row: 1424 Fixed
Row: 1425 Fixed
Row: 1426 Fixed
Row: 1427 Fixed
Row: 1428 Fixed
Row: 1429 Fixed
Row: 1430 Fixed
Row: 1431 Fixed
Row: 1432 Fixed
Row: 1433 Fixed
Row: 1434 Fixed
Row: 1435 Fixed
Row: 1436 Fixed
Row: 1437 Fixed
Row: 1438 Fixed
Row: 1439 Fixed
Row: 1440 Fixed
Row: 1441 Fixed
Row: 1442 Fixed
Row: 1443 Fixed
Row: 1444 Fixed
Row: 1445 Fixed
Row: 1446 Fixed
Row: 1447 Fixed
Row: 1448 Fixed
Row: 1449 Fixed
Row: 1450 Fixed
Row: 1451 Fixed
Row: 1452 Fixed
Row: 1453 Fixed
Row: 1454 Fixed
Row: 1455 Fixed
Row: 1456 Fixed
Row: 1457 Fixed
Row: 1458 Fixed
Row: 1459 Fixed
Row: 1460 Fixed
Row: 1461 Fixed
Row: 1462 Fixed
Row: 1463 Fixed
Row: 1464 Fixed
Row: 1465 Fixed
Row: 1466 Fixed
Row: 1467 Fixed
Row: 1468 Fixed
Row: 1469 Fixed
Row: 1470 Fixed
Row: 1471 Fixed
Row: 1472 Fixed
Row: 1473 Fixed
Row: 1474 Fixed
Row: 1475 Fixed
Row: 1476 Fixed
Row: 1477 Fixed
Row: 1478 Fixed
Row: 1479 Fixed
Row: 1480 Fixed
Row: 1481 Fixed
Row: 1482 Fixed
Row: 1483 Fixed
Row: 1484 Fixed
Row: 1485 Fixed
Row: 1486 Fixed
Row: 1487 Fixed
Row: 1488 Fixed
Row: 1489 Fixed
Row: 1490 Fixed
Row: 1491 Fixed
Row: 1492 Fixed
Row: 1493 Fixed
Row: 1494 Fixed
Row: 1495 Fixed
Row: 1496 Fixed
Row: 1497 Fixed
Row: 1498 Fixed
Row: 1499 Fixed
Row: 1500 Fixed
Row: 1501 Fixed
Row: 1502 Fixed
Row: 1503 Fixed
Row: 1504 Fixed
Row: 1505 Fixed
Row: 1506 Fixed
Row: 1507 Fixed
Row: 1508 Fixed
Row: 1509 Fixed
Row: 1510 Fixed
Row: 1511 Fixed
Row: 1512 Fixed
Row: 1513 Fixed
Row: 1514 Fixed
Row: 1515 Fixed
Row: 1516 Fixed
Row: 1517 Fixed
Row: 1518 Fixed
Row: 1519 Fixed
Row: 1520 Fixed
Row: 1521 Fixed
Row: 1522 Fixed
Row: 1523 Fixed
Row: 1524 Fixed
Row: 1525 Fixed
Row: 1526 Fixed
Row: 1527 Fixed
Row: 1528 Fixed
Row: 1529 Fixed
Row: 1530 Fixed
Row: 1531 Fixed
Row: 1532 Fixed
Row: 1533 Fixed
Row: 1534 Fixed
Row: 1535 Fixed
Row: 1536 Fixed
Row: 1537 Fixed
Row: 1538 Fixed
Row: 1539 Fixed
Row: 1540 Fixed
Row: 1541 Fixed
Row: 1542 Fixed
Row: 1543 Fixed
Row: 1544 Fixed
Row: 1545 Fixed
Row: 1546 Fixed
Row: 1547 Fixed
Row: 1548 Fixed
Row: 1549 Fixed
Row: 1550 Fixed
Row: 1551 Fixed
Row: 1552 Fixed
Row: 1553 Fixed
Row: 1554 Fixed
Row: 1555 Fixed
Row: 1556 Fixed
Row: 1557 Fixed
Row: 1558 Fixed
Row: 1559 Fixed
Row: 1560 Fixed
Row: 1561 Fixed
Row: 1562 Fixed
Row: 1563 Fixed
Row: 1564 Fixed
Row: 1565 Fixed
Row: 1566 Fixed
Row: 1567 Fixed
Row: 1568 Fixed
Row: 1569 Fixed
Row: 1570 Fixed
Row: 1571 Fixed
Row: 1572 Fixed
Row: 1573 Fixed
Row: 1574 Fixed
Row: 1575 Fixed
Row: 1576 Fixed
Row: 1577 Fixed
Row: 1578 Fixed
Row: 1579 Fixed
Row: 1580 Fixed
Row: 1581 Fixed
Row: 1582 Fixed
Row: 1583 Fixed
Row: 1584 Fixed
Row: 1585 Fixed
Row: 1586 Fixed
Row: 1587 Fixed
Row: 1588 Fixed
Row: 1589 Fixed
Row: 1590 Fixed
Row: 1591 Fixed
Row: 1592 Fixed
Row: 1593 Fixed
Row: 1594 Fixed
Row: 1595 Fixed
Row: 1596 Fixed
Row: 1597 Fixed
Row: 1598 Fixed
Row: 1599 Fixed
Row: 1600 Fixed
Row: 1601 Fixed
Row: 1602 Fixed
Row: 1603 Fixed
Row: 1604 Fixed
Row: 1605 Fixed
Row: 1606 Fixed
Row: 1607 Fixed
Row: 1608 Fixed
Row: 1609 Fixed
Row: 1610 Fixed
Row: 1611 Fixed
Row: 1612 Fixed
Row: 1613 Fixed
Row: 1614 Fixed
Row: 1615 Fixed
Row: 1616 Fixed
Row: 1617 Fixed
Row: 1618 Fixed
Row: 1619 Fixed
Row: 1620 Fixed
Row: 1621 Fixed
Row: 1622 Fixed
Row: 1623 Fixed
Row: 1624 Fixed
Row: 1625 Fixed
Row: 1626 Fixed
Row: 1627 Fixed
Row: 1628 Fixed
Row: 1629 Fixed
Row: 1630 Fixed
Row: 1631 Fixed
Row: 1632 Fixed
Row: 1633 Fixed
Row: 1634 Fixed
Row: 1635 Fixed
Row: 1636 Fixed
Row: 1637 Fixed
Row: 1638 Fixed
Row: 1639 Fixed
Row: 1640 Fixed
Row: 1641 Fixed
Row: 1642 Fixed
Row: 1643 Fixed
Row: 1644 Fixed
Row: 1645 Fixed
Row: 1646 Fixed
Row: 1647 Fixed
Row: 1648 Fixed
Row: 1649 Fixed
Row: 1650 Fixed
Row: 1651 Fixed
Row: 1652 Fixed
Row: 1653 Fixed
Row: 1654 Fixed
Row: 1655 Fixed
Row: 1656 Fixed
Row: 1657 Fixed
Row: 1658 Fixed
Row: 1659 Fixed
Row: 1660 Fixed
Row: 1661 Fixed
Row: 1662 Fixed
Row: 1663 Fixed
Row: 1664 Fixed
Row: 1665 Fixed
Row: 1666 Fixed
Row: 1667 Fixed
Row: 1668 Fixed
Row: 1669 Fixed
Row: 1670 Fixed
Row: 1671 Fixed
Row: 1672 Fixed
Row: 1673 Fixed
Row: 1674 Fixed
Row: 1675 Fixed
Row: 1676 Fixed
Row: 1677 Fixed
Row: 1678 Fixed
Row: 1679 Fixed
Row: 1680 Fixed
Row: 1681 Fixed
Row: 1682 Fixed
Row: 1683 Fixed
Row: 1684 Fixed
Row: 1685 Fixed
Row: 1686 Fixed
Row: 1687 Fixed
Row: 1688 Fixed
Row: 1689 Fixed
Row: 1690 Fixed
Row: 1691 Fixed
Row: 1692 Fixed
Row: 1693 Fixed
Row: 1694 Fixed
Row: 1695 Fixed
Row: 1696 Fixed
Row: 1697 Fixed
Row: 1698 Fixed
Row: 1699 Fixed
Row: 1700 Fixed
Row: 1701 Fixed
Row: 1702 Fixed
Row: 1703 Fixed
Row: 1704 Fixed
Row: 1705 Fixed
Row: 1706 Fixed
Row: 1707 Fixed
Row: 1708 Fixed
Row: 1709 Fixed
Row: 1710 Fixed
Row: 1711 Fixed
Row: 1712 Fixed
Row: 1713 Fixed
Row: 1714 Fixed
Row: 1715 Fixed
Row: 1716 Fixed
Row: 1717 Fixed
Row: 1718 Fixed
Row: 1719 Fixed
Row: 1720 Fixed
Row: 1721 Fixed
Row: 1722 Fixed
Row: 1723 Fixed
Row: 1724 Fixed
Row: 1725 Fixed
Row: 1726 Fixed
Row: 1727 Fixed
Row: 1728 Fixed
Row: 1729 Fixed
Row: 1730 Fixed
Row: 1731 Fixed
Row: 1732 Fixed
Row: 1733 Fixed
Row: 1734 Fixed
Row: 1735 Fixed
Row: 1736 Fixed
Row: 1737 Fixed
Row: 1738 Fixed
Row: 1739 Fixed
Row: 1740 Fixed
Row: 1741 Fixed
Row: 1742 Fixed
Row: 1743 Fixed
Row: 1744 Fixed
Row: 1745 Fixed
Row: 1746 Fixed
Row: 1747 Fixed
Row: 1748 Fixed
Row: 1749 Fixed
Row: 1750 Fixed
Row: 1751 Fixed
Row: 1752 Fixed
Row: 1753 Fixed
Row: 1754 Fixed
Row: 1755 Fixed
Row: 1756 Fixed
Row: 1757 Fixed
Row: 1758 Fixed
Row: 1759 Fixed
Row: 1760 Fixed
Row: 1761 Fixed
Row: 1762 Fixed
Row: 1763 Fixed
Row: 1764 Fixed
Row: 1765 Fixed
Row: 1766 Fixed
Row: 1767 Fixed
Row: 1768 Fixed
Row: 1769 Fixed
Row: 1770 Fixed
Row: 1771 Fixed
Row: 1772 Fixed
Row: 1773 Fixed
Row: 1774 Fixed
Row: 1779 Fixed
Row: 1780 Fixed
Row: 1781 Fixed
Row: 1782 Fixed
Row: 1783 Fixed
Row: 1784 Fixed
Row: 1785 Fixed
Row: 1786 Fixed
Row: 1787 Fixed
Row: 1788 Fixed
Row: 1789 Fixed
Row: 1790 Fixed
Row: 1791 Fixed
Row: 1792 Fixed
Row: 1793 Fixed
Row: 1794 Fixed
Row: 1795 Fixed
Row: 1796 Fixed
Row: 1797 Fixed
Row: 1798 Fixed
Row: 1799 Fixed
Row: 1800 Fixed
Row: 1801 Fixed
Row: 1802 Fixed
Row: 1803 Fixed
Row: 1804 Fixed
Row: 1805 Fixed
Row: 1806 Fixed
Row: 1807 Fixed
Row: 1808 Fixed
Row: 1809 Fixed
Row: 1810 Fixed
Row: 1811 Fixed
Row: 1812 Fixed
Row: 1813 Fixed
Row: 1814 Fixed
Row: 1815 Fixed
Row: 1816 Fixed
Row: 1817 Fixed
Row: 1818 Fixed
Row: 1819 Fixed
Row: 1820 Fixed
Row: 1821 Fixed
Row: 1822 Fixed
Row: 1823 Fixed
Row: 1824 Fixed
Row: 1825 Fixed
Row: 1826 Fixed
Row: 1827 Fixed
Row: 1828 Fixed
Row: 1829 Fixed
Row: 1830 Fixed
Row: 1831 Fixed
Row: 1832 Fixed
Row: 1833 Fixed
Row: 1834 Fixed
Row: 1835 Fixed
Row: 1836 Fixed
Row: 1837 Fixed
Row: 1838 Fixed
Row: 1839 Fixed
Row: 1840 Fixed
Row: 1841 Fixed
Row: 1842 Fixed
Row: 1843 Fixed
Row: 1844 Fixed
Row: 1845 Fixed
Row: 1846 Fixed
Row: 1847 Fixed
Row: 1848 Fixed
Row: 1849 Fixed
Row: 1850 Fixed
Row: 1851 Fixed
Row: 1852 Fixed
Row: 1853 Fixed
Row: 1854 Fixed
Row: 1855 Fixed
Row: 1856 Fixed
Row: 1857 Fixed
Row: 1858 Fixed
Row: 1859 Fixed
Row: 1860 Fixed
Row: 1861 Fixed
Row: 1862 Fixed
Row: 1863 Fixed
Row: 1864 Fixed
Row: 1865 Fixed
Row: 1866 Fixed
Row: 1867 Fixed
Row: 1868 Fixed
Row: 1869 Fixed
Row: 1870 Fixed
Row: 1871 Fixed
Row: 1872 Fixed
Row: 1873 Fixed
Row: 1874 Fixed
Row: 1875 Fixed
Row: 1876 Fixed
Row: 1877 Fixed
Row: 1878 Fixed
Row: 1879 Fixed
Row: 1880 Fixed
Row: 1881 Fixed
Row: 1882 Fixed
Row: 1883 Fixed
Row: 1884 Fixed
Row: 1885 Fixed
Row: 1886 Fixed
Row: 1887 Fixed
Row: 1888 Fixed
Row: 1889 Fixed
Row: 1890 Fixed
Row: 1891 Fixed
Row: 1892 Fixed
Row: 1893 Fixed
Row: 1894 Fixed
Row: 1895 Fixed
Row: 1896 Fixed
Row: 1897 Fixed
Row: 1898 Fixed
Row: 1899 Fixed
Row: 1900 Fixed
Row: 1901 Fixed
Row: 1902 Fixed
Row: 1903 Fixed
Row: 1904 Fixed
Row: 1905 Fixed
Row: 1906 Fixed
Row: 1907 Fixed
Row: 1908 Fixed
Row: 1909 Fixed
Row: 1910 Fixed
Row: 1911 Fixed
Row: 1912 Fixed
Row: 1913 Fixed
Row: 1914 Fixed
Row: 1915 Fixed
Row: 1916 Fixed
Row: 1917 Fixed
Row: 1918 Fixed
Row: 1919 Fixed
Row: 1920 Fixed
Row: 1921 Fixed
Row: 1922 Fixed
Row: 1923 Fixed
Row: 1924 Fixed
Row: 1925 Fixed
Row: 1926 Fixed
Row: 1927 Fixed
Row: 1928 Fixed
Row: 1929 Fixed
Row: 1930 Fixed
Row: 1931 Fixed
Row: 1932 Fixed
Row: 1933 Fixed
Row: 1934 Fixed
Row: 1935 Fixed
Row: 1936 Fixed
Row: 1937 Fixed
Row: 1938 Fixed
Row: 1939 Fixed
Row: 1940 Fixed
Row: 1941 Fixed
Row: 1942 Fixed
Row: 1943 Fixed
Row: 1944 Fixed
Row: 1945 Fixed
Row: 1946 Fixed
Row: 1947 Fixed
Row: 1948 Fixed
Row: 1949 Fixed
Row: 1950 Fixed
Row: 1951 Fixed
Row: 1952 Fixed
Row: 1953 Fixed
Row: 1954 Fixed
Row: 1955 Fixed
Row: 2046 Fixed
Row: 2047 Fixed
Row: 2048 Fixed
Row: 2049 Fixed
Row: 2207 Fixed
Row: 2208 Fixed
Row: 2209 Fixed
Row: 2210 Fixed
Row: 2211 Fixed
Row: 2212 Fixed
Row: 2213 Fixed
Row: 2214 Fixed
Row: 2215 Fixed
Row: 2216 Fixed
Row: 2217 Fixed
Row: 2218 Fixed
Row: 2219 Fixed
Row: 2220 Fixed
Row: 2221 Fixed
Row: 2222 Fixed
Row: 2223 Fixed
Row: 2224 Fixed
Row: 2225 Fixed
Row: 2226 Fixed
Row: 2227 Fixed
Row: 2228 Fixed
Row: 2229 Fixed
Row: 2230 Fixed
Row: 2231 Fixed
Row: 2232 Fixed
Row: 2233 Fixed
Row: 2234 Fixed
Row: 2235 Fixed
Row: 2236 Fixed
Row: 2237 Fixed
Row: 2238 Fixed
Row: 2239 Fixed
Row: 2240 Fixed
Row: 2241 Fixed
Row: 2242 Fixed
Row: 2243 Fixed
Row: 2244 Fixed
Row: 2245 Fixed
Row: 2246 Fixed
Row: 2247 Fixed
Row: 2248 Fixed
Row: 2249 Fixed
Row: 2250 Fixed
Row: 2251 Fixed
Row: 2252 Fixed
Row: 2253 Fixed
Row: 2254 Fixed
Row: 2255 Fixed
Row: 2256 Fixed
Row: 2257 Fixed
Row: 2258 Fixed
Row: 2259 Fixed
Row: 2260 Fixed
Row: 2261 Fixed
Row: 2262 Fixed
Row: 2263 Fixed
Row: 2264 Fixed
Row: 2265 Fixed
Row: 2266 Fixed
Row: 2267 Fixed
Row: 2268 Fixed
Row: 2269 Fixed
Row: 2270 Fixed
Row: 2271 Fixed
Row: 2272 Fixed
Row: 2273 Fixed
Row: 2274 Fixed
Row: 2275 Fixed
Row: 2276 Fixed
Row: 2277 Fixed
Row: 2278 Fixed
Row: 2279 Fixed
Row: 2280 Fixed
Row: 2281 Fixed
Row: 2282 Fixed
Row: 2283 Fixed
Row: 2284 Fixed
Row: 2285 Fixed
Row: 2286 Fixed
Row: 2287 Fixed
Row: 2288 Fixed
Row: 2289 Fixed
Row: 2609 Fixed
Row: 2610 Fixed
Row: 2611 Fixed
Row: 2612 Fixed
Row: 2613 Fixed
Row: 2614 Fixed
Row: 2615 Fixed
Row: 2616 Fixed
Row: 2617 Fixed
Row: 2618 Fixed
Row: 2619 Fixed
Row: 2620 Fixed
Row: 2621 Fixed
Row: 2622 Fixed
Row: 2623 Fixed
Row: 2624 Fixed
Row: 2625 Fixed
Row: 2626 Fixed
Row: 2627 Fixed
Row: 2628 Fixed
Row: 2629 Fixed
Row: 2630 Fixed
Row: 2631 Fixed
Row: 2632 Fixed
Row: 2633 Fixed
Row: 2634 Fixed
Row: 2635 Fixed
Row: 2636 Fixed
Row: 2637 Fixed
Row: 2638 Fixed
Row: 2639 Fixed
Row: 2640 Fixed
Row: 2641 Fixed
Row: 2642 Fixed
Row: 2643 Fixed
Row: 2644 Fixed
Row: 2645 Fixed
Row: 2646 Fixed
Row: 2647 Fixed
Row: 2648 Fixed
Row: 2649 Fixed
Row: 2650 Fixed
Row: 2651 Fixed
Row: 2652 Fixed
Row: 2653 Fixed
Row: 2654 Fixed
Row: 2655 Fixed
Row: 2656 Fixed
Row: 2657 Fixed
Row: 2658 Fixed
Row: 2659 Fixed
Row: 2660 Fixed
Row: 2661 Fixed
Row: 2662 Fixed
Row: 2663 Fixed
Row: 2664 Fixed
Row: 2665 Fixed
Row: 2666 Fixed
Row: 2667 Fixed
Row: 2668 Fixed
Row: 2669 Fixed
Row: 2670 Fixed
Row: 2671 Fixed
Row: 2672 Fixed
Row: 2673 Fixed
Row: 2674 Fixed
Row: 2675 Fixed
Row: 2676 Fixed
Row: 2677 Fixed
Row: 2678 Fixed
Row: 2679 Fixed
Row: 2680 Fixed
Row: 2681 Fixed
Row: 2682 Fixed
Row: 2683 Fixed
Row: 2684 Fixed
Row: 2685 Fixed
Row: 2686 Fixed
Row: 2687 Fixed
Row: 2688 Fixed
Row: 2689 Fixed
Row: 2690 Fixed
Row: 2691 Fixed
Row: 2692 Fixed
Row: 2693 Fixed
Row: 2694 Fixed
Row: 2695 Fixed
Row: 2696 Fixed
Row: 2697 Fixed
Row: 2698 Fixed
Row: 2699 Fixed
Row: 2700 Fixed
Row: 2701 Fixed
Row: 2702 Fixed
Row: 2703 Fixed
Row: 2704 Fixed
Row: 2705 Fixed
Row: 2706 Fixed
Row: 2707 Fixed
Row: 2708 Fixed
Row: 2709 Fixed
Row: 2710 Fixed
Row: 2711 Fixed
Row: 2712 Fixed
Row: 2713 Fixed
Row: 2714 Fixed
Row: 2715 Fixed
Row: 2716 Fixed
Row: 2717 Fixed
Row: 2718 Fixed
Row: 2719 Fixed
Row: 2720 Fixed
Row: 2721 Fixed
Row: 2722 Fixed
Row: 2723 Fixed
Row: 2724 Fixed
Row: 2725 Fixed
Row: 2726 Fixed
Row: 2727 Fixed
Row: 2728 Fixed
Row: 2729 Fixed
Row: 2730 Fixed
Row: 2731 Fixed
Row: 2732 Fixed
Row: 2733 Fixed
Row: 2734 Fixed
Row: 2735 Fixed
Row: 2736 Fixed
Row: 2737 Fixed
Row: 2738 Fixed
Row: 2739 Fixed
Row: 2740 Fixed
Row: 2741 Fixed
Row: 2742 Fixed
Row: 2743 Fixed
Row: 2744 Fixed
Row: 2745 Fixed
Row: 2746 Fixed
Row: 2747 Fixed
Row: 2748 Fixed
Row: 2749 Fixed
Row: 2750 Fixed
Row: 2751 Fixed
Row: 2752 Fixed
Row: 2753 Fixed
Row: 2754 Fixed
Row: 2755 Fixed
Row: 2756 Fixed
Row: 2757 Fixed
Row: 2758 Fixed
Row: 2759 Fixed
Row: 2760 Fixed
Row: 2761 Fixed
Row: 2762 Fixed
Row: 2763 Fixed
Row: 2764 Fixed
Row: 2765 Fixed
Row: 2766 Fixed
Row: 2767 Fixed
Row: 2768 Fixed
Row: 2769 Fixed
Row: 2770 Fixed
Row: 2771 Fixed
Row: 2772 Fixed
Row: 2773 Fixed
Row: 2774 Fixed
Row: 2775 Fixed
Row: 2776 Fixed
Row: 2777 Fixed
Row: 2778 Fixed
Row: 2779 Fixed
Row: 2780 Fixed
Row: 2781 Fixed
Row: 2782 Fixed

In [39]:
# Check that the error no longer exists
for row in range(df.shape[0]):
    for card, col in enumerate(card_cols):
        if df.loc[row, col] == 1:
            relevant_range_cols = [
                f"prob_P_has_hand_{conf_hand}" for conf_hand in Hand.HANDS_WITH_CARD[card]
            ] + [f"prob_O_has_hand_{conf_hand}" for conf_hand in Hand.HANDS_WITH_CARD[card]]
            range_sum = df.loc[row, relevant_range_cols].sum()
            if range_sum != 0:
                print("Row:", row, "Card:", card, "conflicts with hands")
                print("Row:", row, "Range sum:", range_sum)
                print("Row:", row, df.loc[row, relevant_range_cols])
                raise Exception("Error still exists")
print("No error in any rows!")

In [40]:
# Make ranges sum to 1
p1_range_cols = [col for col in df.columns if col.startswith("prob_P_has_hand_")]
opponent_range_cols = [col for col in df.columns if col.startswith("prob_O_has_hand_")]
updated_rows = list(updated_rows)
df.loc[updated_rows, p1_range_cols] = df.loc[updated_rows, p1_range_cols].div(
    df.loc[updated_rows, p1_range_cols].sum(axis=1), axis=0
)
df.loc[updated_rows, opponent_range_cols] = df.loc[updated_rows, opponent_range_cols].div(
    df.loc[updated_rows, opponent_range_cols].sum(axis=1), axis=0
)

In [44]:
assert np.allclose(df[p1_range_cols].sum(axis=1), 1, rtol=1e-10)
assert np.allclose(df[opponent_range_cols].sum(axis=1), 1, rtol=1e-10)

In [46]:
# Check that a similar error does not exist for the target variables
for row in range(df.shape[0]):
    for card, col in enumerate(card_cols):
        if df.loc[row, col] == 1:
            relevant_target_cols = [
                f"value_of_hand_{conf_hand}" for conf_hand in Hand.HANDS_WITH_CARD[card]
            ]
            range_sum = df.loc[row, relevant_target_cols].sum()
            if range_sum != 0:
                print("Row:", row, "Card:", card, "conflicts with hands")
                print("Row:", row, "Values for conflicting hands:", range_sum)
                print("Row:", row, df.loc[row, relevant_target_cols])
                raise Exception("The same error exists for the target variables")
print("No error!")

No error!

In [47]:
# Add a column to distinguish between fixed and non-fixed rows
df.loc[:, "origin"] = "after_range_fix"
df.loc[updated_rows, "origin"] = "pre_range_fix_but_fixed"
df

,prob_P_has_hand_0,prob_P_has_hand_1,prob_P_has_hand_2,prob_P_has_hand_3,prob_P_has_hand_4,prob_P_has_hand_5,prob_P_has_hand_6,prob_P_has_hand_7,prob_P_has_hand_8,prob_P_has_hand_9,...,player_bet_in_game,opponent_bet_in_stage,opponent_bet_in_game,player_turn,player_has_bet,opponent_has_bet,pot,game_size,stage,origin
0,0.001377,0.000228,0.001744,0.000486,0.000538,0.000434,0.000950,0.001289,0.000914,0.001696,...,469,40,495,True,True,True,964,1487,river,after_range_fix
1,0.001339,0.000039,0.000013,0.000504,0.000867,0.001299,0.001545,0.000667,0.001549,0.000661,...,119,13,121,True,True,True,240,2003,river,after_range_fix
2,0.000000,0.001377,0.000651,0.000391,0.001705,0.000569,0.000410,0.001504,0.000090,0.000198,...,370,117,377,True,True,True,747,2001,river,after_range_fix
3,0.001162,0.001362,0.000000,0.001594,0.001635,0.001112,0.000135,0.001304,0.000315,0.001661,...,305,325,630,True,True,True,935,2326,river,after_range_fix
4,0.000171,0.000427,0.001027,0.000752,0.000495,0.000646,0.001213,0.000560,0.001425,0.001687,...,180,28,208,True,False,True,388,1088,river,after_range_fix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11007,0.001510,0.001131,0.001499,0.000144,0.000465,0.000000,0.000973,0.001789,0.001542,0.001787,...,103,45,148,True,False,True,251,1333,river,after_range_fix
11008,0.000990,0.001654,0.000506,0.000000,0.000199,0.001468,0.001385,0.001262,0.001167,0.000688,...,409,92,501,True,False,True,910,1907,river,after_range_fix
11009,0.000293,0.000851,0.001572,0.001028,0.000965,0.001796,0.000691,0.001638,0.001164,0.000123,...,143,167,310,True,True,True,453,1442,river,after_range_fix
11010,0.001447,0.000098,0.000460,0.000000,0.000387,0.000091,0.001042,0.000552,0.001136,0.000000,...,439,118,557,True,False,True,996,2194,river,after_range_fix
11011,0.000000,0.000000,0.001349,0.001582,0.000238,0.001067,0.001052,0.001140,0.000851,0.000463,...,393,8,401,True,False,True,794,1867,river,after_range_fix

In [48]:
# Save fixed dataframe to parquet
df.to_parquet("../dfs/fixed_20240430132106.parquet")