In [25]:
import os
import pandas as pd
from datetime import datetime
import importlib
import numpy as np

np.set_printoptions(suppress=True)

In [26]:
# Relative imports
d = os.path.abspath(os.getcwd())
os.chdir("../..")
import hidden_state_model.processor
importlib.reload(hidden_state_model.processor)
Processor = hidden_state_model.processor.Processor
os.chdir(d)

### Read (and compact) dataframes

In [27]:
compact = True

In [28]:
# Iterate over files in dfs/*.parquet and combine to one df
dfs = []

read = []
data_dir = os.path.join(d, "..", "data")
for file in os.listdir(data_dir):
    fname = os.path.join(data_dir, file)
    if file.endswith(".parquet"):
        read.append(file)
        print(f"Reading {file}")
        df = pd.read_parquet(fname)
        dfs.append(df)
    if file.endswith(".csv"):
        read.append(file)
        df = pd.read_csv(fname, index_col=0)
        dfs.append(df)

raw_df = pd.concat(dfs)

if compact and len(dfs) > 10:
    print("Compacintg dfs")

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    raw_df.to_parquet(os.path.join(data_dir, f"combined_{timestamp}.parquet"))

    # Move files already in trash to trash within trash
    trash = os.path.join(data_dir, "trash")
    trash_in_trash = os.path.join(trash, f"trash_{timestamp}")
    os.makedirs(trash_in_trash, exist_ok=True)
    for f in os.listdir(trash):
        if f.endswith(".parquet") or f.endswith(".csv"):
            os.rename(os.path.join(trash, f), os.path.join(trash_in_trash, f))
    
    # Move read files to trash and write combined df to dfs/combined_{timestamp}.parquet
    for f in read:
        os.rename(os.path.join(data_dir, f), os.path.join(trash, f))

dfs = []  # Clear memory
raw_df

Reading combined_20240906175220.parquet

,prev_entry,public_cards,player_piles,current_player_i,bet_in_stage,bet_in_game,player_has_played,player_is_folded,first_better_i,big_blind,...,player_type,opponent_names,action,amount,p,relative_ev,rank,tiebreakers,hand_index,state_id
state_id,,,,,,,,,,,,,,,,,,,,,
cc2a3234-bfcd-4e2b-8bdb-686215485494,None,[],"[98, 96]",0,"[2, 4]","[2, 4]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,2,0.4942,0.014826,0,"[9, 1, 0, 0, 0]",643.0,NaN
4d01fa55-3b5d-4bff-9405-f6d662314da4,cc2a3234-bfcd-4e2b-8bdb-686215485494,"[28, 2, 3]","[96, 96]",0,"[0, 0]","[4, 4]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.3689,0.014756,1,"[2, 9, 3, 1, 0]",643.0,NaN
71edc4a8-d3e2-4dc1-b144-9f3364276d5a,4d01fa55-3b5d-4bff-9405-f6d662314da4,"[28, 2, 3, 37]","[96, 96]",0,"[0, 0]","[4, 4]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.3770,0.015080,1,"[2, 11, 9, 3, 0]",643.0,NaN
664036cc-7bfe-4909-bafe-3cf4d2a315fb,71edc4a8-d3e2-4dc1-b144-9f3364276d5a,"[28, 2, 3, 37, 25]","[96, 96]",0,"[0, 0]","[4, 4]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.4181,0.016724,1,"[2, 12, 11, 9, 0]",643.0,NaN
89023332-7a45-4a9a-bc67-aa216902ad1d,None,[],"[98, 96]",0,"[2, 4]","[2, 4]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,2,0.5425,0.016275,0,"[9, 4, 0, 0, 0]",202.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
da352ecb-0bff-4d97-93c9-0e51b62ddf7c,d78292f2-41a3-4b79-9d80-077941aa6812,[],"[92, 88]",0,"[8, 12]","[8, 12]","[True, True]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,4,0.5355,0.053550,1,"[1, 0, 0, 0, 0]",648.0,NaN
a7dc51a6-de38-4621-bc36-5ac07bb6535b,da352ecb-0bff-4d97-93c9-0e51b62ddf7c,"[8, 51, 24]","[88, 88]",0,"[0, 0]","[12, 12]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],raise,12,0.5032,0.060384,1,"[1, 12, 11, 8, 0]",648.0,NaN
77da9d72-f807-4f77-9320-3e39e963dd1b,a7dc51a6-de38-4621-bc36-5ac07bb6535b,"[8, 51, 24]","[76, 71]",0,"[12, 17]","[24, 29]","[True, True]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,5,0.5032,0.133348,1,"[1, 12, 11, 8, 0]",648.0,NaN
6916adb4-e31f-4708-b5c4-1d93f3f21cb5,77da9d72-f807-4f77-9320-3e39e963dd1b,"[8, 51, 24, 18]","[71, 71]",0,"[0, 0]","[29, 29]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.4546,0.131834,1,"[1, 12, 11, 8, 0]",648.0,NaN
2fddffca-122d-4022-8fa3-06db0c0bc4f8,6916adb4-e31f-4708-b5c4-1d93f3f21cb5,"[8, 51, 24, 18, 15]","[71, 71]",0,"[0, 0]","[29, 29]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.3665,0.106285,1,"[1, 12, 11, 8, 0]",648.0,NaN

In [29]:
raw_df.dtypes

prev_entry            object
public_cards          object
player_piles          object
current_player_i       int64
bet_in_stage          object
bet_in_game           object
player_has_played     object
player_is_folded      object
first_better_i         int64
big_blind              int64
player_name           object
player_type           object
opponent_names        object
action                object
amount                 int64
p                    float64
relative_ev          float64
rank                   int64
tiebreakers           object
hand_index           float64
state_id             float64
dtype: object

In [30]:
# Check for conflicting rows
dupe_df = raw_df[raw_df.index.duplicated()]
dupe_df

Empty DataFrame
Columns: [prev_entry, public_cards, player_piles, current_player_i, bet_in_stage, bet_in_game, player_has_played, player_is_folded, first_better_i, big_blind, player_name, player_type, opponent_names, action, amount, p, relative_ev, rank, tiebreakers, hand_index, state_id]
Index: []

[0 rows x 21 columns]

## Process data

In [31]:
processor = Processor(raw_df)
df = processor.get_processed_df()
df

,raise_preflop,raise_flop,raise_turn,raise_river,raise_showdown,call_preflop,call_flop,call_turn,call_river,call_showdown,...,game_id,action,amount,excess_rank,p,relative_ev,stage,player_name,opponent_name,n_players
5086819376,0,0,0,0,0,0,0,0,0,0,...,7f91d8a0-7684-475a-98a0-82f71b281c95,raise,6,0,0.3057,0.009171,preflop,Tord,,2
092eec64-2a07-498d-a9a7-4baa17a455fa,0,0,0,0,0,0,0,0,0,0,...,6f888850-b69c-4d70-9b8c-3e7e8a74aea0,raise,6,1,0.7036,0.021108,preflop,Tord,,2
4864781280,0,0,0,0,0,0,0,0,0,0,...,8ecfe5fd-4e94-4805-b624-1dfd166390e7,fold,0,0,0.3775,0.022650,preflop,Arin,,2
10901045312,0,0,0,0,0,0,0,0,0,0,...,972cc0a0-ee4a-4d31-a981-487728d1b622,call,2,1,0.6498,0.019494,preflop,Arin,,2
6303798704,0,0,0,0,0,0,0,0,0,0,...,c2da94e3-3146-43a0-941f-b7a02a8064a0,check,0,1,0.7834,0.031336,preflop,Arin,,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6162182496,0,0,0,0,0,8,7,15,0,0,...,3bd7c280-7b0c-4ac6-adc3-a43b252323bf,check,0,0,0.5797,0.185504,river,Arin,,2
6179041536,0,0,0,0,0,6,6,12,0,0,...,eb6d9364-6edb-4fc2-b545-612f6f62d53b,call,17,0,0.1604,0.055338,river,Arin,,2
6086701696,0,0,0,0,0,6,4,4,0,0,...,e93d3b38-4975-4aa5-a6b1-1afacfd82a25,call,29,0,0.0915,0.027907,river,Arin,,2
6190510384,0,0,0,0,0,9,4,10,0,0,...,6fb84287-fd6f-4586-83a1-0c296eb0a41c,call,15,1,0.5748,0.186810,river,Arin,,2
6162184512,0,22,21,0,0,6,5,10,0,0,...,f482535f-6985-46e2-ae2f-f10718127957,check,0,1,0.8571,0.565686,river,Arin,,2

In [32]:
df.dtypes

raise_preflop                int64
raise_flop                   int64
raise_turn                   int64
raise_river                  int64
raise_showdown               int64
call_preflop                 int64
call_flop                    int64
call_turn                    int64
call_river                   int64
call_showdown                int64
check_preflop                int64
check_flop                   int64
check_turn                   int64
check_river                  int64
check_showdown               int64
opponent_raise_preflop       int64
opponent_raise_flop          int64
opponent_raise_turn          int64
opponent_raise_river         int64
opponent_raise_showdown      int64
opponent_call_preflop        int64
opponent_call_flop           int64
opponent_call_turn           int64
opponent_call_river          int64
opponent_call_showdown       int64
opponent_check_preflop       int64
opponent_check_flop          int64
opponent_check_turn          int64
opponent_check_river         int64
opponent_check_showdown      int64
game_id                     object
action                      object
amount                       int64
excess_rank                  int64
p                          float64
relative_ev                float64
stage                       object
player_name                 object
opponent_name               object
n_players                    int64
dtype: object

## Training

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [34]:
X = df.drop(["game_id", "action", "amount"], axis=1)
y = df["action"]
groups = df["game_id"]  # Group by 'game_id' to ensure no data leakage

In [35]:
X

,raise_preflop,raise_flop,raise_turn,raise_river,raise_showdown,call_preflop,call_flop,call_turn,call_river,call_showdown,...,opponent_check_turn,opponent_check_river,opponent_check_showdown,excess_rank,p,relative_ev,stage,player_name,opponent_name,n_players
5086819376,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.3057,0.009171,preflop,Tord,,2
092eec64-2a07-498d-a9a7-4baa17a455fa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0.7036,0.021108,preflop,Tord,,2
4864781280,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.3775,0.022650,preflop,Arin,,2
10901045312,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0.6498,0.019494,preflop,Arin,,2
6303798704,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0.7834,0.031336,preflop,Arin,,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6162182496,0,0,0,0,0,8,7,15,0,0,...,1,1,0,0,0.5797,0.185504,river,Arin,,2
6179041536,0,0,0,0,0,6,6,12,0,0,...,1,1,0,0,0.1604,0.055338,river,Arin,,2
6086701696,0,0,0,0,0,6,4,4,0,0,...,1,1,0,0,0.0915,0.027907,river,Arin,,2
6190510384,0,0,0,0,0,9,4,10,0,0,...,1,1,0,1,0.5748,0.186810,river,Arin,,2
6162184512,0,22,21,0,0,6,5,10,0,0,...,1,1,0,1,0.8571,0.565686,river,Arin,,2

In [36]:
y

5086819376                              raise
092eec64-2a07-498d-a9a7-4baa17a455fa    raise
4864781280                               fold
10901045312                              call
6303798704                              check
                                        ...
6162182496                              check
6179041536                               call
6086701696                               call
6190510384                               call
6162184512                              check
Name: action, Length: 5019, dtype: object

In [37]:
# Identify categorical columns (excluding 'game_id')
categorical_cols = ["excess_rank", "stage", "player_name", "opponent_name"]

# Preprocessing pipeline: OneHotEncoding for categorical and scaling for numerical
preprocessor = ColumnTransformer(
    transformers=[("cat", OneHotEncoder(drop="first"), categorical_cols)],
    remainder="passthrough",
)

# Create the full pipeline with logistic regression
model = Pipeline(
    [
        ("preprocess", preprocessor),
        (
            "classifier",
            LogisticRegression(
                multi_class="multinomial", solver="lbfgs", max_iter=10_000
            ),
        ),
    ]
)

In [38]:
# Grouped train-test split
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

print(f"Train shape: {X_train.shape}")
print(f"Test shape: {X_test.shape}")

Train shape: (4035, 37)
Test shape: (984, 37)

In [39]:
# Train the model
model.fit(X_train, y_train)

# Evaluate the model
accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 0.641260162601626

In [40]:
probabilities = model.predict_proba(X_test)
prob_df = pd.DataFrame(probabilities, columns=model.classes_, index=X_test.index)
prob_df["true"] = y_test.values
prob_df["pred"] = model.predict(X_test)
prob_df["correct"] = prob_df["true"] == prob_df["pred"]
prob_df["goodness"] = prob_df.apply(lambda x: x.get(x["true"]) or 0, axis=1)
print("Accuracy", prob_df["correct"].mean())
print("Mean goodness: ", prob_df["goodness"].mean())
prob_df

Accuracy 0.641260162601626
Mean goodness:  0.5258572617807842

,call,check,fold,raise,true,pred,correct,goodness
6107067488,0.509062,2.754152e-01,8.737165e-02,0.128151,raise,call,False,0.128151
52d11435-668a-4590-8436-5d88d748455a,0.636105,1.366671e-01,1.456593e-01,0.081568,call,call,True,0.636105
10859414048,0.458836,2.935540e-01,2.079106e-01,0.039699,call,call,True,0.458836
6130657360,0.322936,2.664558e-01,3.888016e-01,0.021806,check,fold,False,0.266456
4680321872,0.421915,2.911478e-01,2.528921e-01,0.034045,fold,call,False,0.252892
...,...,...,...,...,...,...,...,...
6162183648,0.992801,2.422239e-05,2.194256e-04,0.006955,raise,call,False,0.006955
6162171888,0.986597,8.860831e-05,2.280687e-05,0.013292,call,call,True,0.986597
6083916272,0.992079,2.160826e-05,1.206092e-03,0.006693,call,call,True,0.992079
6179041536,0.934749,5.295909e-14,6.523317e-02,0.000018,call,call,True,0.934749
6162184512,0.357664,4.120956e-01,3.531447e-07,0.230240,check,check,True,0.412096

In [41]:
# Look at incorrect predictions
print(prob_df[prob_df["correct"] == False].shape[0], "incorrect predictions:")
prob_df[prob_df["correct"] == False]

353 incorrect predictions:

,call,check,fold,raise,true,pred,correct,goodness
6107067488,0.509062,0.275415,0.087372,0.128151,raise,call,False,0.128151
6130657360,0.322936,0.266456,0.388802,0.021806,check,fold,False,0.266456
4680321872,0.421915,0.291148,0.252892,0.034045,fold,call,False,0.252892
60b9af30-0f87-461b-ad09-51f5b5590ffc,0.468989,0.290146,0.199965,0.040901,check,call,False,0.290146
6093027024,0.447523,0.283370,0.232423,0.036684,fold,call,False,0.232423
...,...,...,...,...,...,...,...,...
6076004816,0.005193,0.927895,0.000036,0.066876,raise,check,False,0.066876
6064224576,0.037487,0.555571,0.011440,0.395501,raise,check,False,0.395501
6064257536,0.035505,0.488418,0.002283,0.473794,raise,check,False,0.473794
10994221984,0.033032,0.890571,0.000031,0.076366,raise,check,False,0.076366
6162183648,0.992801,0.000024,0.000219,0.006955,raise,call,False,0.006955

### Compare to XGBoost

In [50]:
from sklearn.calibration import LabelEncoder
from xgboost import XGBClassifier

categorical_cols = ["excess_rank", "stage", "player_name", "opponent_name"]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_cols,
        )
    ],
    remainder="passthrough",
)

label_encoder = LabelEncoder()

# Modify the classifier to XGBClassifier
xgb_model = Pipeline(
    [
        ("preprocess", preprocessor),
        (
            "classifier",
            XGBClassifier(
                objective="multi:softprob",  # for multiclass classification with probability
                eval_metric="mlogloss",
                n_estimators=100,
                max_depth=6,
                learning_rate=0.1,
                verbosity=1,
            ),
        ),
    ]
)
xgb_model

Pipeline(steps=[('preprocess',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['excess_rank', 'stage',
                                                   'player_name',
                                                   'opponent_name'])])),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_sto...
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=100, n_jobs=None,
                               num_parallel_tree=None,
                               objective='multi:softprob', ...))])

In [51]:
print("shape of y", y_train.shape)
y_train_encoded = label_encoder.fit_transform(y_train)
print("shape of y_train_encoded", y_train_encoded.shape)
print("shape of X_train", X_train.shape)
y_train_encoded

shape of y (4035,)
shape of y_train_encoded (4035,)
shape of X_train (4035, 37)

array([3, 3, 2, ..., 1, 0, 0])

In [52]:
xgb_model.fit(X_train, y_train_encoded)

y_test_encoded = label_encoder.transform(y_test)
accuracy = xgb_model.score(X_test, y_test_encoded)
print(f"Accuracy: {accuracy}")

Accuracy: 0.8170731707317073

In [55]:
probabilities = xgb_model.predict_proba(X_test)
prob_df = pd.DataFrame(probabilities, columns=xgb_model.classes_, index=X_test.index)
prob_df["_true"] = y_test_encoded
prob_df["true"] = y_test.values
prob_df["_pred"] = xgb_model.predict(X_test)
prob_df["pred"] = label_encoder.inverse_transform(prob_df["_pred"])
prob_df["correct"] = prob_df["true"] == prob_df["pred"]
prob_df["goodness"] = prob_df.apply(lambda x: x.get(x["_true"]) or 0, axis=1)
print("Accuracy", prob_df["correct"].mean())
print("Mean goodness: ", prob_df["goodness"].mean())
prob_df

Accuracy 0.8170731707317073
Mean goodness:  0.6914080738568418

,0,1,2,3,_true,true,_pred,pred,correct,goodness
6107067488,0.874627,0.017378,0.011367,0.096628,3,raise,0,call,False,0.096628
52d11435-668a-4590-8436-5d88d748455a,0.876896,0.034555,0.039391,0.049157,0,call,0,call,True,0.876896
10859414048,0.469019,0.032941,0.476910,0.021131,0,call,2,fold,False,0.469019
6130657360,0.131297,0.446547,0.400073,0.022084,1,check,1,check,True,0.446547
4680321872,0.342389,0.080661,0.557486,0.019464,2,fold,2,fold,True,0.557486
...,...,...,...,...,...,...,...,...,...,...
6162183648,0.413576,0.032369,0.013131,0.540925,3,raise,3,raise,True,0.540925
6162171888,0.653962,0.086938,0.029251,0.229849,0,call,0,call,True,0.653962
6083916272,0.983904,0.001033,0.000422,0.014641,0,call,0,call,True,0.983904
6179041536,0.945734,0.002705,0.049119,0.002442,0,call,0,call,True,0.945734
6162184512,0.006410,0.966665,0.003298,0.023627,1,check,1,check,True,0.966665

In [75]:
xgb_model.classes_

array([0, 1, 2, 3])