In [1]:
import os
import pandas as pd
from datetime import datetime
import importlib
import numpy as np

np.set_printoptions(suppress=True)

In [2]:
# Relative imports
d = os.path.abspath(os.getcwd())
os.chdir("../..")
import hidden_state_model.processor
importlib.reload(hidden_state_model.processor)
Processor = hidden_state_model.processor.Processor
os.chdir(d)

### Read (and compact) dataframes

In [3]:
compact = True

In [4]:
# Iterate over files in dfs/*.parquet and combine to one df
dfs = []

read = []
data_dir = os.path.join(d, "..", "data")
for file in os.listdir(data_dir):
    fname = os.path.join(data_dir, file)
    if file.endswith(".parquet"):
        read.append(file)
        print(f"Reading {file}")
        df = pd.read_parquet(fname)
        dfs.append(df)
    if file.endswith(".csv"):
        read.append(file)
        df = pd.read_csv(fname, index_col=0)
        dfs.append(df)

raw_df = pd.concat(dfs)

if compact and len(dfs) > 10:
    print("Compacintg dfs")

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    raw_df.to_parquet(os.path.join(data_dir, f"combined_{timestamp}.parquet"))

    # Move files already in trash to trash within trash
    trash = os.path.join(data_dir, "trash")
    trash_in_trash = os.path.join(trash, f"trash_{timestamp}")
    os.makedirs(trash_in_trash, exist_ok=True)
    for f in os.listdir(trash):
        if f.endswith(".parquet") or f.endswith(".csv"):
            os.rename(os.path.join(trash, f), os.path.join(trash_in_trash, f))
    
    # Move read files to trash and write combined df to dfs/combined_{timestamp}.parquet
    for f in read:
        os.rename(os.path.join(data_dir, f), os.path.join(trash, f))

dfs = []  # Clear memory
raw_df

Reading combined_20240908141615.parquet
Reading 2024-09-14_17-36-32.parquet
Reading 2024-09-15_09-09-44.parquet
Reading 2024-09-15_09-23-53.parquet
Reading 2024-09-14_17-23-58.parquet
Reading 2024-09-15_09-11-59.parquet
Reading 2024-09-08_14-18-39.parquet
Reading 2024-09-15_09-30-38.parquet

,prev_entry,public_cards,player_piles,current_player_i,bet_in_stage,bet_in_game,player_has_played,player_is_folded,first_better_i,big_blind,...,player_type,opponent_names,action,amount,p,relative_ev,rank,tiebreakers,hand_index,state_id
state_id,,,,,,,,,,,,,,,,,,,,,
d7017fec-1c32-4005-9cdd-f94e9ea28417,None,[],"[98, 96]",0,"[2, 4]","[2, 4]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],raise,16,0.5003,0.015009,0,"[11, 0, 0, 0, 0]",608.0,NaN
9e6087b9-6d79-4b90-9302-849d7b328ba5,d7017fec-1c32-4005-9cdd-f94e9ea28417,"[41, 31, 17]","[82, 82]",0,"[0, 0]","[18, 18]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.3218,0.057924,0,"[11, 5, 4, 2, 0]",608.0,NaN
29ccf1f9-4e29-4a1d-88bc-53be9a34e3f4,9e6087b9-6d79-4b90-9302-849d7b328ba5,"[41, 31, 17, 23]","[82, 82]",0,"[0, 0]","[18, 18]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],raise,82,0.2672,0.048096,0,"[11, 10, 5, 4, 2]",608.0,NaN
d2fb7009-21a3-4e30-8f67-b91e44aea81b,29ccf1f9-4e29-4a1d-88bc-53be9a34e3f4,"[41, 31, 17, 23, 15]","[0, 0]",0,"[0, 0]","[100, 100]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.2959,0.295900,1,"[2, 11, 10, 5, 0]",608.0,NaN
4be4b289-7768-4376-8273-d07c7904fbca,None,[],"[98, 96]",0,"[2, 4]","[2, 4]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,2,0.4719,0.014157,0,"[6, 1, 0, 0, 0]",1030.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
e29ab61d-2f89-474e-b750-f4ab6620e9d9,e9798fc4-04f6-4bec-b723-985831571e6c,"[3, 12, 20]","[30, 154]",0,"[0, 0]","[8, 8]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.7515,0.060120,1,"[7, 12, 11, 3, 0]",969.0,NaN
752da045-ffdd-4a9b-ac86-a03578d27c8a,e29ab61d-2f89-474e-b750-f4ab6620e9d9,"[3, 12, 20]","[30, 147]",0,"[0, 7]","[8, 15]","[True, True]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,7,0.7515,0.086423,1,"[7, 12, 11, 3, 0]",969.0,NaN
bacb48ca-872f-4b5b-a0e2-86158735e135,752da045-ffdd-4a9b-ac86-a03578d27c8a,"[3, 12, 20, 50]","[23, 147]",0,"[0, 0]","[15, 15]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],raise,10,0.9293,0.139395,2,"[11, 7, 12, 0, 0]",969.0,NaN
99f450ac-7046-4be3-990f-ac657c64a43a,bacb48ca-872f-4b5b-a0e2-86158735e135,"[3, 12, 20, 50]","[13, 127]",0,"[10, 20]","[25, 35]","[True, True]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,10,0.9293,0.278790,2,"[11, 7, 12, 0, 0]",969.0,NaN
6fe557fc-5c0d-424b-ad48-2feb7f252aa8,99f450ac-7046-4be3-990f-ac657c64a43a,"[3, 12, 20, 50, 45]","[3, 127]",0,"[0, 0]","[35, 35]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.9426,0.329910,2,"[11, 7, 12, 0, 0]",969.0,NaN

In [5]:
raw_df.dtypes

prev_entry            object
public_cards          object
player_piles          object
current_player_i       int64
bet_in_stage          object
bet_in_game           object
player_has_played     object
player_is_folded      object
first_better_i         int64
big_blind              int64
player_name           object
player_type           object
opponent_names        object
action                object
amount                 int64
p                    float64
relative_ev          float64
rank                   int64
tiebreakers           object
hand_index           float64
state_id             float64
dtype: object

In [6]:
# Check for conflicting rows
dupe_df = raw_df[raw_df.index.duplicated()]
dupe_df

Empty DataFrame
Columns: [prev_entry, public_cards, player_piles, current_player_i, bet_in_stage, bet_in_game, player_has_played, player_is_folded, first_better_i, big_blind, player_name, player_type, opponent_names, action, amount, p, relative_ev, rank, tiebreakers, hand_index, state_id]
Index: []

[0 rows x 21 columns]

## Process data

In [7]:
processor = Processor(raw_df)
df = processor.get_processed_df()
df

,raise_preflop,raise_flop,raise_turn,raise_river,raise_showdown,call_preflop,call_flop,call_turn,call_river,call_showdown,...,game_id,action,amount,excess_rank,p,relative_ev,stage,player_name,opponent_name,n_players
ddfc0d4d-d2ed-4464-8c60-f9c5f05f060f,0,0,0,0,0,0,0,0,0,0,...,e9976d91-db0b-48e0-97b1-0928dd1d323b,call,2,0,0.4912,0.014736,preflop,Tord,,2
cbbcc7fd-78ae-4d26-9528-7b37c9de6159,0,0,0,0,0,0,0,0,0,0,...,bdc715a9-5b29-426b-b9ce-30efc49a4125,check,0,0,0.4761,0.019044,preflop,Tord,Max Mekker,2
0d5e26f1-71f6-4e86-aba4-6e30c3f27a11,0,0,0,0,0,0,0,0,0,0,...,b968f5ff-3590-4fbe-954e-9b4816a4ac8c,check,0,0,0.5853,0.023412,preflop,Tord,,2
1c4ba6ca-b830-4213-bad5-e713c9a69d91,0,0,0,0,0,0,0,0,0,0,...,70c473e6-3260-44c7-8fcc-5651ff64c4b5,call,2,0,0.5130,0.015390,preflop,Tord,Max Mekker,2
6106915408,0,0,0,0,0,0,0,0,0,0,...,03610225-eeb9-459e-a414-dea990e4663a,call,2,0,0.5631,0.016893,preflop,Arin,,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6162005392,0,36,0,0,0,7,0,0,0,0,...,bd2c4def-049f-4311-b251-bbb097d1ec51,check,0,2,0.9126,0.410670,river,Arin,,2
6165442032,0,69,0,0,0,6,0,0,0,0,...,f7525c8d-93a4-4286-b97a-471be187ce6b,call,13,1,0.7229,0.603621,flop,Arin,,2
6165562320,0,69,0,0,0,6,13,0,0,0,...,f7525c8d-93a4-4286-b97a-471be187ce6b,check,0,2,0.7730,0.695700,turn,Arin,,2
dace556f-9077-40da-a3c2-a099d7edfbea,0,8,0,0,0,6,5,19,0,0,...,e5312eea-124b-48e8-8d23-e1215709e8e5,call,24,1,0.5764,0.299728,river,Jacob,Max Mekker,2
6165583184,0,69,0,0,0,6,13,0,0,0,...,f7525c8d-93a4-4286-b97a-471be187ce6b,check,0,2,0.9015,0.811350,river,Arin,,2

In [8]:
df.dtypes

raise_preflop                int64
raise_flop                   int64
raise_turn                   int64
raise_river                  int64
raise_showdown               int64
call_preflop                 int64
call_flop                    int64
call_turn                    int64
call_river                   int64
call_showdown                int64
check_preflop                int64
check_flop                   int64
check_turn                   int64
check_river                  int64
check_showdown               int64
opponent_raise_preflop       int64
opponent_raise_flop          int64
opponent_raise_turn          int64
opponent_raise_river         int64
opponent_raise_showdown      int64
opponent_call_preflop        int64
opponent_call_flop           int64
opponent_call_turn           int64
opponent_call_river          int64
opponent_call_showdown       int64
opponent_check_preflop       int64
opponent_check_flop          int64
opponent_check_turn          int64
opponent_check_river         int64
opponent_check_showdown      int64
game_id                     object
action                      object
amount                       int64
excess_rank                  int64
p                          float64
relative_ev                float64
stage                       object
player_name                 object
opponent_name               object
n_players                    int64
dtype: object

## Training

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [10]:
X = df.drop(["game_id", "action", "amount"], axis=1)
y = df["action"]
groups = df["game_id"]  # Group by 'game_id' to ensure no data leakage

In [11]:
X

,raise_preflop,raise_flop,raise_turn,raise_river,raise_showdown,call_preflop,call_flop,call_turn,call_river,call_showdown,...,opponent_check_turn,opponent_check_river,opponent_check_showdown,excess_rank,p,relative_ev,stage,player_name,opponent_name,n_players
ddfc0d4d-d2ed-4464-8c60-f9c5f05f060f,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.4912,0.014736,preflop,Tord,,2
cbbcc7fd-78ae-4d26-9528-7b37c9de6159,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.4761,0.019044,preflop,Tord,Max Mekker,2
0d5e26f1-71f6-4e86-aba4-6e30c3f27a11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.5853,0.023412,preflop,Tord,,2
1c4ba6ca-b830-4213-bad5-e713c9a69d91,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.5130,0.015390,preflop,Tord,Max Mekker,2
6106915408,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.5631,0.016893,preflop,Arin,,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6162005392,0,36,0,0,0,7,0,0,0,0,...,1,0,0,2,0.9126,0.410670,river,Arin,,2
6165442032,0,69,0,0,0,6,0,0,0,0,...,0,0,0,1,0.7229,0.603621,flop,Arin,,2
6165562320,0,69,0,0,0,6,13,0,0,0,...,1,0,0,2,0.7730,0.695700,turn,Arin,,2
dace556f-9077-40da-a3c2-a099d7edfbea,0,8,0,0,0,6,5,19,0,0,...,1,1,0,1,0.5764,0.299728,river,Jacob,Max Mekker,2
6165583184,0,69,0,0,0,6,13,0,0,0,...,2,0,0,2,0.9015,0.811350,river,Arin,,2

In [12]:
y

ddfc0d4d-d2ed-4464-8c60-f9c5f05f060f     call
cbbcc7fd-78ae-4d26-9528-7b37c9de6159    check
0d5e26f1-71f6-4e86-aba4-6e30c3f27a11    check
1c4ba6ca-b830-4213-bad5-e713c9a69d91     call
6106915408                               call
                                        ...
6162005392                              check
6165442032                               call
6165562320                              check
dace556f-9077-40da-a3c2-a099d7edfbea     call
6165583184                              check
Name: action, Length: 6295, dtype: object

In [13]:
# Identify categorical columns (excluding 'game_id')
categorical_cols = ["excess_rank", "stage", "player_name", "opponent_name"]

# Preprocessing pipeline: OneHotEncoding for categorical and scaling for numerical
preprocessor = ColumnTransformer(
    transformers=[("cat", OneHotEncoder(drop="first"), categorical_cols)],
    remainder="passthrough",
)

# Create the full pipeline with logistic regression
model = Pipeline(
    [
        ("preprocess", preprocessor),
        (
            "classifier",
            LogisticRegression(
                multi_class="multinomial", solver="lbfgs", max_iter=10_000
            ),
        ),
    ]
)

In [14]:
# Grouped train-test split
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

print(f"Train shape: {X_train.shape}")
print(f"Test shape: {X_test.shape}")

Train shape: (5070, 37)
Test shape: (1225, 37)

In [15]:
# Train the model
model.fit(X_train, y_train)

# Evaluate the model
accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 0.626938775510204

In [23]:
probabilities = model.predict_proba(X_test)
prob_df = pd.DataFrame(probabilities, columns=model.classes_, index=X_test.index)
prob_df["true"] = y_test.values
prob_df["pred"] = model.predict(X_test)
prob_df["correct"] = prob_df["true"] == prob_df["pred"]
prob_df["goodness"] = prob_df.apply(lambda x: x.get(x["true"]) or 0, axis=1)
prob_df["player_name"] = df.iloc[test_idx]["player_name"]
print("Accuracy", prob_df["correct"].mean())
print("Mean goodness: ", prob_df["goodness"].mean())
prob_df

Accuracy 0.626938775510204
Mean goodness:  0.5191812735162088

,call,check,fold,raise,true,pred,correct,goodness,player_name
6438916976,0.277375,2.277189e-01,4.773611e-01,0.017545,fold,fold,True,0.477361,Arin
230e32d6-55a0-4e60-9b8a-932cfe1c057a,0.456616,2.660637e-01,1.841006e-01,0.093220,fold,call,False,0.184101,Tord
9ecd27f9-5552-46dd-86cb-1618b2951ad6,0.753863,1.090584e-01,8.071821e-02,0.056361,call,call,True,0.753863,Tord
39e947f7-8b3f-4d2a-aca1-12f1ec4219d1,0.752679,5.867589e-02,1.369533e-01,0.051692,call,call,True,0.752679,t
360374be-8723-420e-ba5d-d885cad9b5a0,0.539826,3.383027e-02,3.435132e-03,0.422909,raise,call,False,0.422909,Tord
...,...,...,...,...,...,...,...,...,...
4ee78247-61f2-4dda-aa33-a875b0d735c4,0.705581,9.160104e-07,2.937220e-01,0.000696,fold,call,False,0.293722,t
6305322368,0.993065,4.048050e-08,6.757174e-03,0.000178,call,call,True,0.993065,Arin
6162550992,0.690713,1.853781e-03,3.048900e-01,0.002543,call,call,True,0.690713,Arin
6162544336,0.002659,9.967373e-01,7.277924e-07,0.000603,check,check,True,0.996737,Arin
6162661184,0.987030,1.153773e-02,1.942687e-04,0.001238,call,call,True,0.987030,Arin

In [25]:
prob_df.pivot_table("goodness", "player_name", aggfunc="mean").sort_values(by="goodness")

             goodness
player_name
Arin Bavian  0.358085
Finn         0.404064
Alun         0.417896
Tord         0.506580
Jacob        0.538279
t            0.548318
Arin         0.553681

In [17]:
# Look at incorrect predictions
print(prob_df[prob_df["correct"] == False].shape[0], "incorrect predictions:")
prob_df[prob_df["correct"] == False]

457 incorrect predictions:

,call,check,fold,raise,true,pred,correct,goodness
230e32d6-55a0-4e60-9b8a-932cfe1c057a,0.456616,2.660637e-01,0.184101,9.321956e-02,fold,call,False,0.184101
360374be-8723-420e-ba5d-d885cad9b5a0,0.539826,3.383027e-02,0.003435,4.229088e-01,raise,call,False,0.422909
6129737296,0.501778,2.543804e-01,0.130641,1.132007e-01,check,call,False,0.254380
5861394176,0.375924,2.609938e-01,0.298981,6.410103e-02,check,call,False,0.260994
6161775248,0.553170,2.581699e-01,0.131434,5.722617e-02,check,call,False,0.258170
...,...,...,...,...,...,...,...,...
5425048544,0.050273,8.094756e-01,0.000003,1.402489e-01,raise,check,False,0.140249
6f7e8c98-b1e2-4a2f-bc8f-fb17f86bf8bf,0.851810,4.232693e-05,0.056132,9.201587e-02,fold,call,False,0.056132
f8a54576-195d-492b-950d-226e607c32fb,0.999995,1.723314e-33,0.000003,2.857601e-06,fold,call,False,0.000003
6152140064,0.788685,1.417516e-49,0.211315,9.376518e-10,fold,call,False,0.211315
4ee78247-61f2-4dda-aa33-a875b0d735c4,0.705581,9.160104e-07,0.293722,6.956510e-04,fold,call,False,0.293722

### Compare to XGBoost

In [18]:
from sklearn.calibration import LabelEncoder
from xgboost import XGBClassifier

categorical_cols = ["excess_rank", "stage", "player_name", "opponent_name"]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_cols,
        )
    ],
    remainder="passthrough",
)

label_encoder = LabelEncoder()

# Modify the classifier to XGBClassifier
xgb_model = Pipeline(
    [
        ("preprocess", preprocessor),
        (
            "classifier",
            XGBClassifier(
                objective="multi:softprob",  # for multiclass classification with probability
                eval_metric="mlogloss",
                n_estimators=100,
                max_depth=6,
                learning_rate=0.1,
                verbosity=1,
            ),
        ),
    ]
)
xgb_model

Pipeline(steps=[('preprocess',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['excess_rank', 'stage',
                                                   'player_name',
                                                   'opponent_name'])])),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_sto...
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=100, n_jobs=None,
                               num_parallel_tree=None,
                               objective='multi:softprob', ...))])

In [19]:
print("shape of y", y_train.shape)
y_train_encoded = label_encoder.fit_transform(y_train)
print("shape of y_train_encoded", y_train_encoded.shape)
print("shape of X_train", X_train.shape)
y_train_encoded

shape of y (5070,)
shape of y_train_encoded (5070,)
shape of X_train (5070, 37)

array([0, 1, 1, ..., 1, 0, 1])

In [20]:
xgb_model.fit(X_train, y_train_encoded)

y_test_encoded = label_encoder.transform(y_test)
accuracy = xgb_model.score(X_test, y_test_encoded)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7885714285714286

In [21]:
probabilities = xgb_model.predict_proba(X_test)
prob_df = pd.DataFrame(probabilities, columns=xgb_model.classes_, index=X_test.index)
prob_df["_true"] = y_test_encoded
prob_df["true"] = y_test.values
prob_df["_pred"] = xgb_model.predict(X_test)
prob_df["pred"] = label_encoder.inverse_transform(prob_df["_pred"])
prob_df["correct"] = prob_df["true"] == prob_df["pred"]
prob_df["goodness"] = prob_df.apply(lambda x: x.get(x["_true"]) or 0, axis=1)
print("Accuracy", prob_df["correct"].mean())
print("Mean goodness: ", prob_df["goodness"].mean())
prob_df

Accuracy 0.7885714285714286
Mean goodness:  0.6785254690351383

,0,1,2,3,_true,true,_pred,pred,correct,goodness
6438916976,0.262268,0.207247,0.495656,0.034829,2,fold,2,fold,True,0.495656
230e32d6-55a0-4e60-9b8a-932cfe1c057a,0.780627,0.058064,0.117782,0.043526,2,fold,0,call,False,0.117782
9ecd27f9-5552-46dd-86cb-1618b2951ad6,0.482603,0.033900,0.429243,0.054253,0,call,0,call,True,0.482603
39e947f7-8b3f-4d2a-aca1-12f1ec4219d1,0.808574,0.018723,0.148400,0.024303,0,call,0,call,True,0.808574
360374be-8723-420e-ba5d-d885cad9b5a0,0.387842,0.101451,0.001837,0.508870,3,raise,3,raise,True,0.508870
...,...,...,...,...,...,...,...,...,...,...
4ee78247-61f2-4dda-aa33-a875b0d735c4,0.635704,0.016087,0.338985,0.009223,2,fold,0,call,False,0.338985
6305322368,0.957110,0.016899,0.018169,0.007822,0,call,0,call,True,0.957110
6162550992,0.839609,0.009049,0.140938,0.010404,0,call,0,call,True,0.839609
6162544336,0.001869,0.982463,0.005490,0.010178,1,check,1,check,True,0.982463
6162661184,0.993395,0.001953,0.003163,0.001489,0,call,0,call,True,0.993395

In [22]:
xgb_model.classes_

array([0, 1, 2, 3])