In [1]:
import os
import pandas as pd
from datetime import datetime
import importlib
import numpy as np

np.set_printoptions(suppress=True)

In [2]:
# Relative imports
d = os.path.abspath(os.getcwd())
os.chdir("../..")
import hidden_state_model.processor
importlib.reload(hidden_state_model.processor)
Processor = hidden_state_model.processor.Processor
os.chdir(d)

### Read (and compact) dataframes

In [3]:
compact = True

In [4]:
# Iterate over files in dfs/*.parquet and combine to one df
dfs = []

read = []
data_dir = os.path.join(d, "..", "data")
for file in os.listdir(data_dir):
    fname = os.path.join(data_dir, file)
    if file.endswith(".parquet"):
        read.append(file)
        print(f"Reading {file}")
        df = pd.read_parquet(fname)
        dfs.append(df)
    if file.endswith(".csv"):
        read.append(file)
        df = pd.read_csv(fname, index_col=0)
        dfs.append(df)

raw_df = pd.concat(dfs)

if compact and len(dfs) > 10:
    print("Compacintg dfs")

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    raw_df.to_parquet(os.path.join(data_dir, f"combined_{timestamp}.parquet"))

    # Move files already in trash to trash within trash
    trash = os.path.join(data_dir, "trash")
    trash_in_trash = os.path.join(trash, f"trash_{timestamp}")
    os.makedirs(trash_in_trash, exist_ok=True)
    for f in os.listdir(trash):
        if f.endswith(".parquet") or f.endswith(".csv"):
            os.rename(os.path.join(trash, f), os.path.join(trash_in_trash, f))
    
    # Move read files to trash and write combined df to dfs/combined_{timestamp}.parquet
    for f in read:
        os.rename(os.path.join(data_dir, f), os.path.join(trash, f))

dfs = []  # Clear memory
raw_df

Reading combined_20240908141615.parquet
Reading 2024-09-14_17-36-32.parquet
Reading 2024-09-15_09-09-44.parquet
Reading 2024-09-15_09-23-53.parquet
Reading 2024-09-14_17-23-58.parquet
Reading 2024-09-15_09-11-59.parquet
Reading 2024-09-08_14-18-39.parquet
Reading 2024-09-15_09-30-38.parquet

,prev_entry,public_cards,player_piles,current_player_i,bet_in_stage,bet_in_game,player_has_played,player_is_folded,first_better_i,big_blind,...,player_type,opponent_names,action,amount,p,relative_ev,rank,tiebreakers,hand_index,state_id
state_id,,,,,,,,,,,,,,,,,,,,,
d7017fec-1c32-4005-9cdd-f94e9ea28417,None,[],"[98, 96]",0,"[2, 4]","[2, 4]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],raise,16,0.5003,0.015009,0,"[11, 0, 0, 0, 0]",608.0,NaN
9e6087b9-6d79-4b90-9302-849d7b328ba5,d7017fec-1c32-4005-9cdd-f94e9ea28417,"[41, 31, 17]","[82, 82]",0,"[0, 0]","[18, 18]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.3218,0.057924,0,"[11, 5, 4, 2, 0]",608.0,NaN
29ccf1f9-4e29-4a1d-88bc-53be9a34e3f4,9e6087b9-6d79-4b90-9302-849d7b328ba5,"[41, 31, 17, 23]","[82, 82]",0,"[0, 0]","[18, 18]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],raise,82,0.2672,0.048096,0,"[11, 10, 5, 4, 2]",608.0,NaN
d2fb7009-21a3-4e30-8f67-b91e44aea81b,29ccf1f9-4e29-4a1d-88bc-53be9a34e3f4,"[41, 31, 17, 23, 15]","[0, 0]",0,"[0, 0]","[100, 100]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.2959,0.295900,1,"[2, 11, 10, 5, 0]",608.0,NaN
4be4b289-7768-4376-8273-d07c7904fbca,None,[],"[98, 96]",0,"[2, 4]","[2, 4]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,2,0.4719,0.014157,0,"[6, 1, 0, 0, 0]",1030.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
e29ab61d-2f89-474e-b750-f4ab6620e9d9,e9798fc4-04f6-4bec-b723-985831571e6c,"[3, 12, 20]","[30, 154]",0,"[0, 0]","[8, 8]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.7515,0.060120,1,"[7, 12, 11, 3, 0]",969.0,NaN
752da045-ffdd-4a9b-ac86-a03578d27c8a,e29ab61d-2f89-474e-b750-f4ab6620e9d9,"[3, 12, 20]","[30, 147]",0,"[0, 7]","[8, 15]","[True, True]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,7,0.7515,0.086423,1,"[7, 12, 11, 3, 0]",969.0,NaN
bacb48ca-872f-4b5b-a0e2-86158735e135,752da045-ffdd-4a9b-ac86-a03578d27c8a,"[3, 12, 20, 50]","[23, 147]",0,"[0, 0]","[15, 15]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],raise,10,0.9293,0.139395,2,"[11, 7, 12, 0, 0]",969.0,NaN
99f450ac-7046-4be3-990f-ac657c64a43a,bacb48ca-872f-4b5b-a0e2-86158735e135,"[3, 12, 20, 50]","[13, 127]",0,"[10, 20]","[25, 35]","[True, True]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],call,10,0.9293,0.278790,2,"[11, 7, 12, 0, 0]",969.0,NaN
6fe557fc-5c0d-424b-ad48-2feb7f252aa8,99f450ac-7046-4be3-990f-ac657c64a43a,"[3, 12, 20, 50, 45]","[3, 127]",0,"[0, 0]","[35, 35]","[False, False]","[False, False]",0,4,...,HumanPlayer,[Max Mekker],check,0,0.9426,0.329910,2,"[11, 7, 12, 0, 0]",969.0,NaN

In [5]:
raw_df.dtypes

prev_entry            object
public_cards          object
player_piles          object
current_player_i       int64
bet_in_stage          object
bet_in_game           object
player_has_played     object
player_is_folded      object
first_better_i         int64
big_blind              int64
player_name           object
player_type           object
opponent_names        object
action                object
amount                 int64
p                    float64
relative_ev          float64
rank                   int64
tiebreakers           object
hand_index           float64
state_id             float64
dtype: object

In [6]:
# Check for conflicting rows
dupe_df = raw_df[raw_df.index.duplicated()]
assert len(dupe_df) == 0, dupe_df

## Process data

In [7]:
processor = Processor(raw_df)
df = processor.get_processed_df()
df

,raise_preflop,raise_flop,raise_turn,raise_river,raise_showdown,call_preflop,call_flop,call_turn,call_river,call_showdown,...,game_id,action,amount,excess_rank,p,relative_ev,stage,player_name,opponent_name,n_players
6138956480,0,0,0,0,0,0,0,0,0,0,...,cfe491c1-6f4a-4da9-b031-178fb93b4494,raise,8,0,0.5230,0.015690,preflop,Arin Bavian,,2
3ca7d536-17db-4180-acb0-f621b7e3c3ee,0,0,0,0,0,0,0,0,0,0,...,1f920b63-33ab-45cb-92cf-668b1afbe16d,call,2,0,0.5697,0.017091,preflop,Arin,,2
4843967728,0,0,0,0,0,0,0,0,0,0,...,ede97325-1776-426a-baad-e98d639676e3,call,2,0,0.4542,0.013626,preflop,Tord,,2
6118365552,0,0,0,0,0,0,0,0,0,0,...,4d660c00-f51e-483b-ad78-b659b16b9dca,check,0,0,0.5142,0.020568,preflop,Arin,,2
6162607552,0,0,0,0,0,0,0,0,0,0,...,dcebb910-7ad0-4c85-bba3-b57af4cb72ac,fold,0,0,0.4610,0.013830,preflop,Arin,,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6303798032,69,0,0,0,0,2,0,0,0,0,...,f5ec46ed-e996-43a4-a2c0-8841c29e50c1,check,0,1,0.8202,0.598746,river,Arin,,2
ed1efcec-254d-4356-a88b-0f41f6970ba6,17,0,0,0,0,8,20,7,0,0,...,9f399826-1a3a-4fc5-b61b-27d3b3b4701d,call,12,1,0.5328,0.319680,river,Tord,,2
65198114-ef6e-4915-8973-dfb408b0188e,0,6,40,0,0,6,7,4,0,0,...,0360119c-01dd-4f01-99af-af8805427a7a,call,29,0,0.0927,0.073696,river,Jacob,Max Mekker,2
6174779616,0,0,0,0,0,8,5,22,0,0,...,3c48e15f-94c3-4327-9210-49cbf93c6de2,call,12,0,0.1573,0.067639,river,Arin,,2
6095534304,0,0,0,0,0,8,7,4,0,0,...,33f93aef-5a48-4c39-a4c3-7fa330899bb5,call,43,0,0.3190,0.135575,river,Arin,,2

In [8]:
df.dtypes

raise_preflop                int64
raise_flop                   int64
raise_turn                   int64
raise_river                  int64
raise_showdown               int64
call_preflop                 int64
call_flop                    int64
call_turn                    int64
call_river                   int64
call_showdown                int64
check_preflop                int64
check_flop                   int64
check_turn                   int64
check_river                  int64
check_showdown               int64
opponent_raise_preflop       int64
opponent_raise_flop          int64
opponent_raise_turn          int64
opponent_raise_river         int64
opponent_raise_showdown      int64
opponent_call_preflop        int64
opponent_call_flop           int64
opponent_call_turn           int64
opponent_call_river          int64
opponent_call_showdown       int64
opponent_check_preflop       int64
opponent_check_flop          int64
opponent_check_turn          int64
opponent_check_river         int64
opponent_check_showdown      int64
game_id                     object
action                      object
amount                       int64
excess_rank                  int64
p                          float64
relative_ev                float64
stage                       object
player_name                 object
opponent_name               object
n_players                    int64
dtype: object

## Training

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [10]:
X = df.drop(["excess_rank", "game_id", "p", "relative_ev"], axis=1)
y = df["excess_rank"]
groups = df["game_id"]  # Group by 'game_id' to ensure no data leakage

In [11]:
X

,raise_preflop,raise_flop,raise_turn,raise_river,raise_showdown,call_preflop,call_flop,call_turn,call_river,call_showdown,...,opponent_check_flop,opponent_check_turn,opponent_check_river,opponent_check_showdown,action,amount,stage,player_name,opponent_name,n_players
6138956480,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,raise,8,preflop,Arin Bavian,,2
3ca7d536-17db-4180-acb0-f621b7e3c3ee,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,call,2,preflop,Arin,,2
4843967728,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,call,2,preflop,Tord,,2
6118365552,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,check,0,preflop,Arin,,2
6162607552,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,fold,0,preflop,Arin,,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6303798032,69,0,0,0,0,2,0,0,0,0,...,1,1,0,0,check,0,river,Arin,,2
ed1efcec-254d-4356-a88b-0f41f6970ba6,17,0,0,0,0,8,20,7,0,0,...,1,1,1,0,call,12,river,Tord,,2
65198114-ef6e-4915-8973-dfb408b0188e,0,6,40,0,0,6,7,4,0,0,...,1,1,1,0,call,29,river,Jacob,Max Mekker,2
6174779616,0,0,0,0,0,8,5,22,0,0,...,1,1,1,0,call,12,river,Arin,,2
6095534304,0,0,0,0,0,8,7,4,0,0,...,1,1,1,0,call,43,river,Arin,,2

In [12]:
y

6138956480                              0
3ca7d536-17db-4180-acb0-f621b7e3c3ee    0
4843967728                              0
6118365552                              0
6162607552                              0
                                       ..
6303798032                              1
ed1efcec-254d-4356-a88b-0f41f6970ba6    1
65198114-ef6e-4915-8973-dfb408b0188e    0
6174779616                              0
6095534304                              0
Name: excess_rank, Length: 6295, dtype: int64

In [13]:
# Identify categorical columns (excluding 'game_id')
categorical_cols = ["action", "stage", "player_name", "opponent_name"]

# Preprocessing pipeline: OneHotEncoding for categorical and scaling for numerical
preprocessor = ColumnTransformer(
    transformers=[("cat", OneHotEncoder(drop="first"), categorical_cols)],
    remainder="passthrough",
)

# Create the full pipeline with logistic regression
model = Pipeline(
    [
        ("preprocess", preprocessor),
        (
            "classifier",
            LogisticRegression(
                multi_class="multinomial", solver="lbfgs", max_iter=10_000
            ),
        ),
    ]
)

In [14]:
# Grouped train-test split
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

print(f"Train shape: {X_train.shape}")
print(f"Test shape: {X_test.shape}")

Train shape: (5033, 36)
Test shape: (1262, 36)

In [15]:
# Train the model
model.fit(X_train, y_train)

# Evaluate the model
accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7638668779714739

In [16]:
probabilities = model.predict_proba(X_test)
prob_df = pd.DataFrame(probabilities, columns=model.classes_, index=X_test.index)
prob_df["true"] = y_test.values
prob_df["pred"] = model.predict(X_test)
prob_df["correct"] = prob_df["true"] == prob_df["pred"]
prob_df["goodness"] = prob_df.apply(lambda x: x.get(x["true"]) or 0, axis=1)
print("Accuracy", prob_df["correct"].mean())
print("Mean goodness: ", prob_df["goodness"].mean())
prob_df

Accuracy 0.7638668779714739
Mean goodness:  0.6851937579349866

,0,1,2,3,4,5,true,pred,correct,goodness
6162607552,0.995695,0.004230,0.000016,0.000028,0.000010,0.000020,0,0,True,0.995695
adc0f91b-1779-4e44-83f4-67612589093e,0.953961,0.045240,0.000120,0.000141,0.000146,0.000393,0,0,True,0.953961
6108205648,0.995695,0.004230,0.000016,0.000028,0.000010,0.000020,0,0,True,0.995695
6073718048,0.958248,0.041193,0.000081,0.000127,0.000079,0.000270,0,0,True,0.958248
515af76e-7ed0-49c0-8e3b-480985a3ffd1,0.941090,0.058321,0.000117,0.000151,0.000114,0.000206,0,0,True,0.941090
...,...,...,...,...,...,...,...,...,...,...
6182257328,0.054862,0.575112,0.219275,0.105887,0.036163,0.008701,2,1,False,0.219275
6165583184,0.003696,0.731965,0.064442,0.131594,0.036848,0.031454,2,1,False,0.064442
6118450464,0.398380,0.561672,0.013133,0.006991,0.003757,0.016067,0,1,False,0.398380
6162819776,0.350236,0.604859,0.011791,0.009417,0.007213,0.016484,0,1,False,0.350236
cad5dcf5-7f24-4541-9413-d57fe2f037a9,0.559968,0.409201,0.023722,0.002581,0.000018,0.004510,0,0,True,0.559968

In [17]:
# Look at incorrect predictions
print(prob_df[prob_df["correct"] == False].shape[0], "incorrect predictions:")
prob_df[prob_df["correct"] == False]

298 incorrect predictions:

,0,1,2,3,4,5,true,pred,correct,goodness
72242bd4-77b3-4581-9d5d-29ece4db5dfe,0.707126,0.283889,0.004357,0.002131,0.001194,0.001302,1,0,False,0.283889
6140929504,0.908442,0.088806,0.001025,0.000425,0.000268,0.001035,1,0,False,0.088806
6269848928,0.452375,0.515414,0.023472,0.003570,0.002477,0.002692,0,1,False,0.452375
49e432b3-8e14-40a2-9f2b-47b5a6fff490,0.424131,0.561096,0.002341,0.006072,0.001858,0.004503,0,1,False,0.424131
6269869600,0.253017,0.682388,0.047814,0.006451,0.005255,0.005075,0,1,False,0.253017
...,...,...,...,...,...,...,...,...,...,...
6184176944,0.402073,0.497783,0.023063,0.018224,0.036819,0.022037,0,1,False,0.402073
6182257328,0.054862,0.575112,0.219275,0.105887,0.036163,0.008701,2,1,False,0.219275
6165583184,0.003696,0.731965,0.064442,0.131594,0.036848,0.031454,2,1,False,0.064442
6118450464,0.398380,0.561672,0.013133,0.006991,0.003757,0.016067,0,1,False,0.398380
6162819776,0.350236,0.604859,0.011791,0.009417,0.007213,0.016484,0,1,False,0.350236

### Attempt to infer card probabilities from rank and table

In [18]:
from cpp_poker.cpp_poker import Hand, CardCollection, HandRank, CheatSheet

In [19]:
hand_ranks_per_state = []
table_ranks = []
for i, (state_id, row) in enumerate(prob_df.iterrows()):
    raw_row = raw_df.loc[state_id]
    table_cards = CardCollection(raw_row["public_cards"])
    table_rank = table_cards.rank_hand().get_rank()
    excess_hand_ranks_row = table_cards.rank_all_hands()
    hand_ranks_per_state.append(
        [rank.get_rank() - table_rank for rank in excess_hand_ranks_row]
    )
    table_ranks.append(table_rank)

table_ranks_df = pd.DataFrame(table_ranks, index=prob_df.index, columns=["table_rank"])
hand_ranks_df = pd.DataFrame(hand_ranks_per_state, index=prob_df.index)
hand_ranks_df

,0,1,2,3,4,5,6,7,8,9,...,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325
6162607552,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
adc0f91b-1779-4e44-83f4-67612589093e,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6108205648,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6073718048,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
515af76e-7ed0-49c0-8e3b-480985a3ffd1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6182257328,0,0,0,0,1,0,4,1,1,0,...,2,1,1,1,1,1,1,4,0,0
6165583184,0,1,0,0,0,0,1,0,1,0,...,1,4,0,1,1,1,2,0,1,1
6118450464,1,1,1,4,0,0,0,1,1,0,...,2,1,1,1,1,1,1,0,0,0
6162819776,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
cad5dcf5-7f24-4541-9413-d57fe2f037a9,1,0,0,0,0,0,0,1,0,1,...,1,2,1,2,1,4,1,1,2,1

In [20]:
# Get the values of the column indices from hand_ranks_df
column_indices = hand_ranks_df.values

# Use np.arange to create an array of row indices
row_indices = np.arange(hand_ranks_df.shape[0])[:, None]

# Use the row and column indices to index into the DataFrame values
hand_probs_df = pd.DataFrame(
    prob_df.values[row_indices, column_indices],
    index=hand_ranks_df.index,
    columns=hand_ranks_df.columns,
)

# Normalize the hand probabilities to sum to 1 for each row
hand_probs_df = hand_probs_df.div(hand_probs_df.sum(axis=1), axis=0)
hand_probs_df

,0,1,2,3,4,5,6,7,8,9,...,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325
6162607552,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,...,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801
adc0f91b-1779-4e44-83f4-67612589093e,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,...,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799
6108205648,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,...,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801,0.000801
6073718048,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,...,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799,0.000799
515af76e-7ed0-49c0-8e3b-480985a3ffd1,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798,...,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798,0.000798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6182257328,0.000151,0.000151,0.000151,0.000151,0.001581,0.000151,0.000099,0.001581,0.001581,0.000151,...,0.000603,0.001581,0.001581,0.001581,0.001581,0.001581,0.001581,0.000099,0.000151,0.000151
6165583184,0.000008,0.001656,0.000008,0.000008,0.000008,0.000008,0.001656,0.000008,0.001656,0.000008,...,0.001656,0.000083,0.000008,0.001656,0.001656,0.001656,0.000146,0.000008,0.001656,0.001656
6118450464,0.000979,0.000979,0.000979,0.000007,0.000695,0.000695,0.000695,0.000979,0.000979,0.000695,...,0.000023,0.000979,0.000979,0.000979,0.000979,0.000979,0.000979,0.000695,0.000695,0.000695
6162819776,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886,...,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886,0.000886
cad5dcf5-7f24-4541-9413-d57fe2f037a9,0.000725,0.000992,0.000992,0.000992,0.000992,0.000992,0.000992,0.000725,0.000992,0.000725,...,0.000725,0.000042,0.000725,0.000042,0.000725,0.0,0.000725,0.000725,0.000042,0.000725

In [21]:
# Validate that rows sum to 1
hand_probs_df.sum(axis=1)

6162607552                              1.0
adc0f91b-1779-4e44-83f4-67612589093e    1.0
6108205648                              1.0
6073718048                              1.0
515af76e-7ed0-49c0-8e3b-480985a3ffd1    1.0
                                       ...
6182257328                              1.0
6165583184                              1.0
6118450464                              1.0
6162819776                              1.0
cad5dcf5-7f24-4541-9413-d57fe2f037a9    1.0
Length: 1262, dtype: object

In [22]:
# Look at the max probabilites for different hands
mask = prob_df["pred"] == 2
max_probs = hand_probs_df[mask].max(axis=1)
min_probs = hand_probs_df[mask].min(axis=1)
max_prob_hands = hand_probs_df[mask].idxmax(axis=1)
min_prob_hands = hand_probs_df[mask].idxmin(axis=1)
mean_probs = hand_probs_df[mask].mean(axis=1)
sample_prob_df = pd.DataFrame(
    {
        "max_prob": max_probs,
        "max_prob_hand": max_prob_hands,
        "min_prob": min_probs,
        "min_prob_hand": min_prob_hands,
        "mean_prob": mean_probs,
    }
)
sample_prob_df["max_prob_hand"] = sample_prob_df["max_prob_hand"].apply(lambda x: Hand(x).str())
sample_prob_df["min_prob_hand"] = sample_prob_df["min_prob_hand"].apply(lambda x: Hand(x).str())
sample_prob_df["table"] = raw_df.loc[sample_prob_df.index, "public_cards"].apply(
    lambda x: CardCollection(x).str()
)
sample_prob_df["predicted_excess_rank"] = prob_df.loc[sample_prob_df.index, "pred"]
sample_prob_df["pred_rank"] = (
    sample_prob_df["predicted_excess_rank"]
    + table_ranks_df.loc[sample_prob_df.index, "table_rank"]
)
sample_prob_df["pred_rank_str"] = sample_prob_df["pred_rank"].apply(
    lambda x: HandRank(int(x), []).get_rank_name()
)
sample_prob_df = sample_prob_df.drop(["predicted_excess_rank"], axis=1)
sample_prob_df

,max_prob,max_prob_hand,min_prob,min_prob_hand,mean_prob,table,pred_rank,pred_rank_str
128528be-ee7b-45f3-93e6-126decd13d2d,0.00179,♥ 10 ♥ J,0.00002,♦ 2 ♦ 3,0.000754,♥ 8 ♦ 10 ♦ Q ♦ A ♠ J,2,Two Pairs
aedd4186-32ef-4cb7-9e90-be2f0a5e8c20,0.039716,♥ 10 ♦ 10,0.0,♥ 2 ♥ 3,0.000754,♦ 9 ♦ J ♣ 10 ♠ 8 ♠ 10,3,Three of a Kind
6085936656,0.002048,♥ 5 ♥ 6,0.000033,♥ 2 ♥ 3,0.000754,♥ A ♦ 6 ♣ Q ♠ 5,2,Two Pairs
6086080400,0.003137,♥ 5 ♥ 6,0.000057,♥ 2 ♥ 3,0.000754,♥ A ♦ 6 ♣ Q ♠ 5,2,Two Pairs

In [23]:
# Deepdive into a specific row
state_id = sample_prob_df.index[0]
row = sample_prob_df.loc[state_id]
most_likely_hands = hand_probs_df.loc[state_id].sort_values(ascending=False).head(5)
least_likely_hands = hand_probs_df.loc[state_id].sort_values(ascending=True).head(5)
print("Table cards:", row["table"])
print("Predicted excess rank:", prob_df.loc[state_id, "pred"])
print("Actual excess rank", df.loc[state_id, "excess_rank"])
print("Most and least likely hands:")
for hand, prob in most_likely_hands.items():
    print(f"{Hand(hand).str()}: {prob*100:.2f}%")
print("...")
for hand, prob in least_likely_hands.items():
    print(f"{Hand(hand).str()}: {prob*100:.2f}%")

Table cards: ♥ 8 ♦ 10 ♦ Q ♦ A ♠ J
Predicted excess rank: 2
Actual excess rank 2
Most and least likely hands:
♦ J ♠ 8 : 0.18%
♥ J ♠ Q : 0.18%
♣ A ♠ 8 : 0.18%
♥ Q ♦ J : 0.18%
♦ J ♣ A : 0.18%
...
♦ 4 ♦ 7 : 0.00%
♦ 2 ♦ 5 : 0.00%
♦ 2 ♦ 6 : 0.00%
♦ 2 ♦ 7 : 0.00%
♦ 2 ♦ 8 : 0.00%

:

### Attempt to infer winning probabilities from hidden state probabilities

In [24]:
hand_winning_probs = []
for i, (state_id, row) in enumerate(hand_probs_df.iterrows()):
    print(f"Processing row {i}", flush=True)
    raw_row = raw_df.loc[state_id]
    table_cards = CardCollection(raw_row["public_cards"])
    processed_row = df.loc[state_id]
    n_players = processed_row["n_players"]
    hand_winning_probs.append(CheatSheet.get_all_winning_probabilities(table_cards, n_players, 1000))

hand_winning_probs_df = pd.DataFrame(hand_winning_probs, index=hand_probs_df.index)
hand_winning_probs_df

Processing row 0
Processing row 1Cache is not loaded, loading cache

Setting up signal handlers
Processing row 2
Processing row 3
Processing row 4
Processing row 5
Processing row 6
Processing row 7
Processing row 8
Processing row 9
Processing row 10
Processing row 11
Processing row 12
Processing row 13
Processing row 14
Processing row 15
Processing row 16
Processing row 17
Processing row 18
Processing row 19
Processing row 20
Processing row 21
Processing row 22
Processing row 23
Processing row 24
Processing row 25